### ISSUE TITLE
Update Go libraries

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1009]
Update to newer versions

**Comment by nilsgstrabo** [comment]
Updating the following repos:

radix-acr-cleanup
radix-api
DONE radix-canary-golang
radix-canarycicd-test-1
radix-canarycicd-test-2
radix-canarycicd-test-3
radix-canarycicd-test-4
radix-cicd-canary
radix-cli
radix-cluster-cleanup
DONE radix-common
radix-cost-allocation
radix-cost-allocation-api
radix-github-actions
radix-github-webhook
radix-image-scanner
radix-job-scheduler
radix-log-api
radix-networkpolicy-canary
MASTER radix-operator
radix-private
radix-public-site
radix-servicenow-proxy
radix-tekton
radix-velero-plugin
radix-vulnerability-scanner
radix-vulnerability-scanner-api
radix-web-console
