### ISSUE TITLE
Configure audit logging from AKS clusters

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1023]
As per today the logging has been done and stored centrally by policies issued by Omnia team.

They will now longer store log centrally - for cost issues

WR1211 -> TR2375 https://docmap.equinor.com/Docmap/page/doc/dmDocIndex.html?DOCKEYID=1000005127

Talk to Solum for advice:
What is required?
What is the cost today?
Retention?

-----------------
We're reaching out to you regarding Kubernetes and WR1211 12.4.1: Event logging.
 
At present, we are centralizing the Kubernetes audit logs to ensure compliance with company policies.
 
In order to minimize duplicate data and reduce costs, we have made the decision to remove Kubernetes Audit logs, as it’s by far the highest hitter on cost.
Starting 04.09.2023 we will remove the following Diagnostic Category settings from your Kubernetes instance:
-              Kubernetes Audit
-              guard
Which is today being routed to OCP-Management(701c4434-5576-44ad-844c-d0804a253e6a), oms-europe or oms-europe-sox.
 
It's therefore paramount that you still follow WR1211 12.4.1 for your own Kubernetes cluster.
One suggestion is to enable “Kubernetes Audit Admin Logs” for all environments and turn off or delete clusters that is not in use, to minimize cost.
 
Best regards,
Omnia Operations / Solum

**Comment by sveinpj** [comment]
![Image](https://github.com/equinor/radix-platform/assets/83902071/58258427-5642-45c2-b53e-5c64c26bf3b8)
