### ISSUE TITLE
Change logging library for Go applications

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-platform#1048]
Change Go logging library in the following applications

- [x] https://github.com/equinor/radix-acr-cleanup/issues/74
- [x] https://github.com/equinor/radix-cluster-cleanup/issues/35
- [x] https://github.com/equinor/radix-cost-allocation-api/issues/107
- [x] https://github.com/equinor/radix-networkpolicy-canary/issues/21
- [x] https://github.com/equinor/radix-velero-plugin/issues/51
- [x] https://github.com/equinor/radix-vulnerability-scanner/issues/38
- [x] https://github.com/equinor/radix-vulnerability-scanner-api/issues/15
- [x] https://github.com/equinor/radix-tekton/issues/110
- [x] https://github.com/equinor/radix-cost-allocation/issues/113
- [ ] https://github.com/equinor/radix-github-webhook/issues/84
- [ ] https://github.com/equinor/radix-job-scheduler/issues/113
- [x] https://github.com/equinor/radix-log-api/issues/19
- [x] https://github.com/equinor/radix-servicenow-proxy/issues/15
- [ ] https://github.com/equinor/radix-api/issues/596
- [ ] https://github.com/equinor/radix-operator/issues/1047

**Is your feature request related to a problem? Please describe.**
Currently our logging library (logrus) is slow, and limited support for structured logging. This makes it overly hard to troubleshoot bugs.

**Describe the solution you'd like**
Start using structured logging

**Describe alternatives you've considered**
I think there are 4 relevant solutions:
- Keep using logrus, but start using the structured output (slow)
- Migrate to slog (new golang standard log library)
- Migrate to zerolog (apparantly twice as fast as slog. Interresting, but very different logging API from slog and logrus)
- Migrate to zerolog, but introduce our own interface matching slog/log (I assume this will be equall to or slower than slog)
- Look into Zap, almost same performance as Zerolog, similar/same API as log/slog

Performance testing from Uber/Zap: https://github.com/uber-go/zap#performance
Log a message and 10 fields:

| Package | Time | Time % to zap | Objects Allocated |
| :------ | :--: | :-----------: | :---------------: |
| zerolog | 380 ns/op | -42% | 1 allocs/op
| zap | 656 ns/op | +0% | 5 allocs/op
|  zap (sugared) | 935 ns/op | +43% | 10 allocs/op
| go-kit | 2249 ns/op | +243% | 57 allocs/op
| slog (LogAttrs) | 2479 ns/op | +278% | 40 allocs/op
| slog | 2481 ns/op | +278% | 42 allocs/op
| apex/log | 9591 ns/op | +1362% | 63 allocs/op
| log15 | 11393 ns/op | +1637% | 75 allocs/op
| logrus | 11654 ns/op | +1677% | 79 allocs/op

## Zerolog:
```go
log.Debug().
    Str("Scale", "833 cents").
    Float64("Interval", 833.09).
    Msg("Fibonacci is everywhere")
```

## slog:
```go
slog.Info("Fibonacci is everywhere", 
    "Scale", "833 cents"
    "Interval", 833,09,
    )
```

## zap:
```go
// Sugar log:
sugar.Infow("Fibonacci is everywhere",
  "Scale",  "833 cents"
  "Interval", 833,09,
  )

// Fastest:
logger.Info("Fibonacci is everywhere",
  zap.String("Scale",  "833 cents"),
  zap.Float6("Interval", 833,09),
  )
```

## logrus
```go
  log.WithFields(log.Fields{
    "Scale":    "833 cents",
    "Interval": 833,09,
  })
  .Info("Fibonacci is everywhere")
```

**Comment by sondresjolyst** [comment]
ref: https://github.com/equinor/radix-cicd-canary/pull/175
