### ISSUE TITLE
OAuth2 feature: route nginx auth request to internal oauth2-proxy service instead of its public ingress

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-platform#1052]
The OAuth2 feature in Radix adds multiple annotations to the Ingress object. These annotations are read by ingress-nginx and is used to configure misc directives in nginx.conf.

The annotation `nginx.ingress.kubernetes.io/auth-url` is used to configure the `auth_request` directive. When nginx receives a request, it will do a sub-request to the URL defined in `auth_request` to validate if the request is authentication or not. We set this URL to the public DNS name(s) for the component. This works as long as the DNS name is public. However, if an application defines an externalDNSName that is not public (e.g. foo.statoil.no), nginx is unable to resolve the host name in the URL, and responds to the caller with status 500.

To fix this issue, we can change the value of the `nginx.ingress.kubernetes.io/auth-url` annotation to point to the K8S Service defined for the oauth2 component, e.g. `web-aux-oauth.oauth-demo-dev.svc.cluster.local` where `web-aux-oauth` is the service name, `oauth-demo-dev` is the namespace and `svc.cluster.local` is K8S's internal DNS suffix.

The annotations for the OAuth2 feature are built by [this code](https://github.com/equinor/radix-operator/blob/0a626d4a63bf19656e5bfbb66d1985198962e815/pkg/apis/deployment/ingressannotationprovider.go#L91)

**Comment by emirgens** [comment]
Nice introduction to radix-operator for Richard
