### ISSUE TITLE
Implement ExternalSecretsOperator to simplify secrets management [security]

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-platform#1082]
**Is your feature request related to a problem? Please describe.**
rotating secrets. 

**Describe the solution you'd like**
Install https://external-secrets.io/latest/provider/azure-key-vault// to sync secrets from our KeyVault to our cluster, and rotate our secrets automatically when changed in keyvault.

**Describe alternatives you've considered**
Shell scripts and terraform commands to update secrets.

**Additional context**
Azure Key Vault provider works great both with kubelet managed identity and Workload Identity. They provide both a SecretStore (available for secrets in the same namespace) and ClusterSecretStore available for all namespaces, as well as ExternalSecret (creates a k8s secret synced with KeyVault secret in a specific namespace) and a ClusterExternalSecret that can create a secret in any namespace that matches a selector.

By default secrets are synced hourly.

We still need a way to make sure services have he new secret before the old one is expired, even when the secret is updated (restart a deployment)
(Maybe https://github.com/stakater/Reloader can be checked out, or manually maintain a list of services with when and how their secres are rotated... Or both. Reloader is untested by me)

Prepare External Secrets Operator
- [x]  #1165 
- [x] https://github.com/equinor/radix-monitoring/issues/68
- [x] platform
- [x] c2
- [x] playground

Install External Secrets Operator
- [x] dev #1166 
- [x] playground 
- [x] platform
- [x] c2
- [x] extmon https://github.com/equinor/radix-monitoring/issues/68

Move secrets to be managed by External Secrets Operator
- [x] Grafana
- [x] Prometheus
- [x] Velero
- [ ] Cost allocation db user
- [x] Vulnerability scan db user
- [ ] radix-app-registry-secret-dev

Update documentation for new component in radix-private

- [x] https://github.com/equinor/radix-private/issues/221

---------
**DoD**
Secrets Operator installed

Flux configuration in place for Secrets Operator
Managed Identity for all clusters 
The following Secrets managed by the Secrets Operator:
Grafana Oauth, Prometheus, Velero, Cost allocation db user, Vulnerability scan db user, radix-app-registry-secret-dev
- [ ] [extmon](https://github.com/equinor/radix-monitoring/issues/67)

**Comment by emirgens** [comment]
**Iteration 1** - Spike - Explore the tool - Define a "Definition of Done" for implementation
