### ISSUE TITLE
Webhook that can be used for CI job

### ISSUE THREAD

**Issue by flyrev** [equinor/radix-platform#109]
It would be very convenient if a (simple) CI job (`docker build .` or something along the lines of `docker build --target=test .` could be run by Radix as part of a pull request flow.

Our team has three applications running in Radix (autorepgen, skjermen and govdoc) that would all benefit from this. Two of them are using a simple Travis CI file which only runs `docker build .` for verification (we have written our `Dockerfile`s  so that tests are part of build, not a separate stage).

Depending on the complexity involved, a start could be to provide a separate webhook which will run `docker build .` (non-configurable) and then expand from there.

**Comment by oyron** [comment]
Old issue. Verified with @atleh that this is no longer needed by Team Awesome. Closing the issue. If other teams would like to request such functionality, please create a new issue.
