### ISSUE TITLE
s940-ANVM/c2 not working

### ISSUE THREAD

**Issue by sveinpj** [equinor/radix-platform#1096]

**Comment by sveinpj** [comment]
Det virker ut som ANM har fungerer
Se 2 peerings med AN i navnet:
https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/cluster-vnet-hub-c2/providers/Microsoft.Network/virtualNetworks/vnet-hub/peerings

**Comment by sondresjolyst** [comment]
la de manuelt inn i ANVM sånn den lager peeringen.

https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters/providers/Microsoft.Network/networkManagers/s940-ANVM/networkGroups/c2/mrsg_settings_memberVirtualNetwork
