### ISSUE TITLE
Change cost allocation / vulnerability scanner DB admin account with azure account

### ISSUE THREAD

**Issue by sondresjolyst** [equinor/radix-platform#1107]
Azure SQL Database should have Microsoft Entra Only Authentication enabled
To disable local authentication methods and only allow Azure Active Directory authentication:
1. Find your Azure Sql server in the portal.
2. Navigate to Microsoft Entra ID in the left navigation pane.
3. Select "Set admin" if Microsoft Entra ID admin is not already set.
4. Check the "Support only Microsoft Entra ID authentication for this server" box and press "Save"

# Vulnerability scanner
- [x] https://github.com/equinor/radix-platform/pull/1169
- [x] https://github.com/equinor/radix-platform/pull/1172   Playground 
- [x] https://github.com/equinor/radix-platform/pull/1173 C2 + Platform
- [ ] https://github.com/equinor/radix-vulnerability-scanner/pull/39
- [ ] https://github.com/equinor/radix-cost-allocation/pull/114

**Comment by emirgens** [comment]
1. Create Managed Identity for each database when a database is created
2. Create SQL user for this MI
3. Add SQL user in dbo group of the server
4. Create federated credential for this MI for GitHub actions
5. Update GitHub action

**Comment by Richard87** [comment]
# Vulnerability Scanner
 - Create Managed Identity
 - Create Federated credentials for Github Actions
 - Optional Terraform
   - Create database
   - Create db credentials - store in key vaults
   - Create private links
 - optional kubernetes
   -  create federated credentials for Azure Workload Identity

# Cost
