### ISSUE TITLE
Solution for backup of Container Registry

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1145]
Radix container registry does not have a good backup, in Disaster Recovery case this will improve the Time To Recover dramatically.

- [ ] Ask Microsoft, what are the recommend solution/action - Support request sent: 2406180050003792 @Richard87 
      > No speceific solution, recommended a Policy to block deletion and activating soft delete
- [ ] Put into an extra ACR as a backup
- [ ] Restore functionality

**Comment by Richard87** [comment]
Response from microsoft: Use Management Policies to avoid accidental deletion

Added CanNotDelete lock to avoid accidental deletion
