### ISSUE TITLE
Change Keyvault access permission model -> Azure role-based access control 

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1164]
Permission model
Grant data plane access by using a [Azure RBAC](https://learn.microsoft.com/azure/role-based-access-control/overview?WT.mc_id=Portal-Microsoft_Azure_KeyVault) or [Key Vault access policy](https://learn.microsoft.com/azure/key-vault/general/assign-access-policy-portal?WT.mc_id=Portal-Microsoft_Azure_KeyVault)

Change from **Vault access policy** to **Azure role-based access control**

- [ ] Assign all existing users/apps the applicable Access role
- [ ] Change the Permission model

Today access permissions Get, List -> will have new role Key vault Secrets User
Today access permissions Get, List, Update -> will have new role Key vault secrets officer

**Comment by sveinpj** [comment]
New Keyvaults created with RBAC model
