### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by lindvarl** [equinor/radix-platform#118]
Change the git clone from:
   git clone git@github.com:equinor/jsv-das-radix.git -b master --progress .
to:  
 git clone --recurse-submodules git@github.com:equinor/jsv-das-radix.git -b master --progress .

Application name in Radix: 
jsv-das

Application component: 
das-deviation-api

Cluster: 
https://web-radix-web-console-prod.beta-9.radix.equinor.com
https://console.playground.radix.equinor.com

**Comment by thezultimate** [comment]
This feature has been implemented using `--recurse-submodules` for public submodules.
