### ISSUE TITLE
Upgrade logging to ContainerLogV2 

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-platform#1258]
Enable ContainerLogV2 to simplify query logs and have consistency between zones

https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-data-collection-configmap

https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-data-collection-configmap
https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml

`k get cm -n kube-system container-azm-ms-aks-k8scluster -o yaml`

> Prerequisites
> - ConfigMap is a global list and there can be only one ConfigMap applied to the agent for Container insights. Applying another ConfigMap will overrule the previous ConfigMap collection settings.
> - The minimum agent version supported to collect stdout, stderr, and environmental variables from container workloads is ciprod06142019 or later. To verify your agent version, on the Node tab, select a node. On the Properties pane, note the value of the Agent Image Tag property. For more information about the agent versions and what's included in each release, see [Agent release notes](https://github.com/microsoft/Docker-Provider/tree/ci_feature_prod).

**Comment by nilsgstrabo** [comment]
ContainerLogV2 is enabled in AKS monitoring setting, and we don't need to use the configmap
