### ISSUE TITLE
Is it possible to provide build-time secrets?

### ISSUE THREAD

**Issue by nemzes** [equinor/radix-platform#128]
From @flyrev:

We need to authenticate with a feed in Azure DevOps as part of the image building process. We are retrieving internal NuGet packages as part of the build process.

In this particular case it is a licensing/IP issue. We are using a library which is neither written nor owned by Equinor. The code itself is not available. We receive the binaries for the library and add them as dependencies. Instead of having the binaries in every repository that needs it, creating a package of it and making it available through a private feed seems like the best way to handle this.

**Comment by Brynjulf** [comment]
Me and the team I am on would like to see this issue resolved, we have an npm package that is on the internal equinor npm registry.

**Comment by jgvabo** [comment]
@equinor/omnia-radix - can you provide an update on the status of this issue? Has it been added to the backlog? If so - with what priority? We'd like to move the REP client & client API, but we need to pull some packages from the Equinor internal npm registry, and thus require this functionality

**Comment by emirgens** [comment]
This is registered in our backlog and placed in the list of prioritised stories. However it is not possible to say when it will be started on/finished.

Our ref: https://equinor.atlassian.net/browse/RA-71

**Comment by ingeknudsen** [comment]
We have now delivered a feature for defining build secrets on Radix. Please see https://www.radix.equinor.com/docs/reference-radix-config/#build for more info. Let us know if you find any issues with the solution

**Comment by jgvabo** [comment]
Thanks!
