### ISSUE TITLE
Deleting an orphaned environment "stays" on url for deleted environment

### ISSUE THREAD

**Issue by larskaare** [equinor/radix-platform#138]
When i delete an orphaned environment - i’m getting a “empty” page (same url as for the environment when it was available). I would have expected and “env. deleted” or a redirect to the app url in the console …

Application name in Radix: Echo
Cluster: Playground

**Comment by ingeknudsen** [comment]
Will close this issue as it has been fixed. Web console gives the following message after deleting:
"Environment removal has started but it may take a while to be completely removed"
