### ISSUE TITLE
radixconfig.yaml - possibility to add branch filter in environment.build.from

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#147]
It would be very useful to be able to specify a branch filter in the radixconfig build.from for an environment, for example
```
name: qa
  build:
    from: /release/**/*
```
to pick up any new release branch or any changes to a release branch and deploy to qa.
(example uses ant-style wildcards https://confluence.jetbrains.com/display/TCD18/Wildcards )

**Comment by emirgens** [comment]
Thanks for reporting this
Added in the Radix product backlog: https://equinor.atlassian.net/browse/RA-326.
The product owner will prioritize this issue, and may contact you for further details.

**Comment by keaaa** [comment]
This will be investigated and hopefully implemented this sprint

**Comment by emirgens** [comment]
This feature has now been implemented in Radix Platform.
More info here: https://www.radix.equinor.com/docs/reference-radix-config/#overview

**Comment by ingeknudsen** [comment]
Close issue as it has been solved, and bug-fixes fixed
