### ISSUE TITLE
web console - jobs: manually create build/deploy job without an automatic build pipeline

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#148]
Currently the web console only supports manually starting one of the pipelines specified in radixconfig. For example with the basic setup
```environments:
    - name: dev
      build:
        from: dev
    - name: test
      build:
        from: dev
    - name: qa
      build:
        from: master
    - name: prod
```
you only get the option to build and deploy to dev and test from the dev branch or to qa from the master branch, no options to build and deploy to prod.

It would be useful to be able to start a build and deploy for an environment without having it also automatically trigger on git commit. It could be a flag in the radixconfig to so that pipeline has to be manually started (`build.on-commit: true/false` or similar). 

Alternatively allow manually starting a job for any available branch to any environment, unless that is deemed too risky.

**Comment by emirgens** [comment]
Added to Radix product backlog: https://equinor.atlassian.net/browse/RA-327

**Comment by emirgens** [comment]
As agreed - closing this
