### ISSUE TITLE
web console - test runs/dashboard and report publishing

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#150]
It would be very useful to be able to set up test build steps in/as a pipeline, and extract and publish test reports, typically in jUnit or xUnit format. At least a subset of what is available in azure devops or jenkins/teamcity for test build steps.

**Comment by emirgens** [comment]
Product Backlog ref.: https://equinor.atlassian.net/browse/RA-331

**Comment by emirgens** [comment]
This have not been evaluated by the Radix team together with the Product Owner, and decided that this will not be provided.
