### ISSUE TITLE
web console - manually promote deployment to another environment

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#151]
The radix workflow guide mentions 
`Finally, if preprod is working fine, we can then manually promote the deployment to the prod environment`.
This workflow is apparently not available in production yet. It would be very useful to have this in order to be able to properly do prod deployments which usually shouldn't trigger on a git commit.

**Comment by emirgens** [comment]
This is registered in the Radix product backlog. I've linked this issue to the card.
https://equinor.atlassian.net/browse/RA-101

**Comment by keaaa** [comment]
Radix team will run a spike this sprint to agree on how promotion will work, they will contact you for input.

**Comment by nemzes** [comment]
This has now been released. Happy promoting!
