### ISSUE TITLE
Feature request: ability to change AD Group with Radix management rights after application has been created.

### ISSUE THREAD

**Issue by thiagonplo** [equinor/radix-platform#155]
Thanks for taking the time to report an issue or feature request.

If applicable, please provide the following information:

Application name in Radix: 

Application component: 

Cluster:

**Comment by emirgens** [comment]
A similar issue has already been registered and been added to our Product Backlog. I'll "link" these together.
Ref: https://github.com/equinor/radix-platform/issues/88
Backlog ref.: https://equinor.atlassian.net/browse/RA-125

**Comment by nemzes** [comment]
This has been released in the latest web console (3.2.0)
