### ISSUE TITLE
Total file transfer size limit

### ISSUE THREAD

**Issue by chiangs** [equinor/radix-platform#156]
Application name in Radix: js-well-exp

Conditions: Normal POST request from Web App Client to upload files to Azure Blob Storage through .NET Core 2.2 Web API.

On local environment any number of files, file size and total transfer size works.

On Radix environments 1mb is the total transfer size. 

Requesting the limit for total transfer size be increased to min 20 mb - 100mb.

**Comment by nemzes** [comment]
Jira issue: RA-362

**Comment by nemzes** [comment]
@chiangs can you confirm that you're no longer getting the file size issue? The limit has been raised.

**Comment by chiangs** [comment]
@nemzes I was able to upload a 21.4mb file. As discussed I've set my app to upload one file at a time.

**Comment by nemzes** [comment]
Cool. The limit is currently set at 100MB.
