### ISSUE TITLE
Consol.radix fails to load if the browser blocks third-party cookies 

### ISSUE THREAD

**Issue by soofstad** [equinor/radix-platform#164]
If the browser is set to block "Third-Party Cookies", the loading of the radix console fails.
Error message;
![2019-06-24 14 26 13 console playground radix equinor com aa4b6c16c8c6](https://user-images.githubusercontent.com/11062560/60020251-f071f280-968f-11e9-9613-d5fde30ed9f8.png)

Testet with Chrome, Firefox, and Vivaldi.
If the browser is set to accept cookies from "visited" sites, the page loads successfully.

**Comment by emirgens** [comment]
Thanks for reporting this. It has been added to the product backlog ready to be prioritised.

https://equinor.atlassian.net/browse/RA-428

**Comment by nemzes** [comment]
After investigating it's clear that it's not possible for us to allow logging in without third-party cookies, at least not with the current infrastructure we use.

The current message is quite cryptic. We will try to address how this is communicated in the UI as part of addressing a somewhat-related bug (https://equinor.atlassian.net/browse/RA-369).
/close
