### ISSUE TITLE
Commit message flags (e.g to skip builds)

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#165]
Noticed this when I was working on altering our docker file due to some build-problems. After I had sorted the file and had everything working, I wanted to clean up the file. This causes yet another build to be triggered by the pipeline, which is pointless. It would be good if certain commit flags could be used, which would in turn cause Radix to ignore the commit.

E.g:
`git commit -m "Fix a thing"` -> cause a build
`git commit -m "Fix a thing [skip-build]"` -> ignore build

This could also be expanded later on, with tags like [build-<component>] to only rebuild one of the images, rather than rebuilding all components if just one has a change.

**Comment by emirgens** [comment]
Thanks for providing us with input like this. We have registered this in our backlog and it will be prioritised by our Product Owner.
Jira ref.: 
https://equinor.atlassian.net/browse/RA-430

**Comment by emirgens** [comment]
We have now reviewed our list of feature requests. Sorry your request will not be done.

Radix team
