### ISSUE TITLE
Manual deployment rollback

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#166]
Somewhat related to https://github.com/equinor/radix-platform/issues/151
It would be useful to be able to roll back a deployment to a previous, working deployment.

**Comment by emirgens** [comment]
We've added it to our backlog

Ref.: https://equinor.atlassian.net/browse/RA-436

**Comment by nemzes** [comment]
This has been implemented; for details check https://www.radix.equinor.com/guides/deployment-promotion/
