### ISSUE TITLE
Missing 'space' in environmnent list build from same branch

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#180]
Application name in Radix:
`loss-control`

Cluster: 
`production`

---

When radix application has multiple environments build from same branch, then they'll be listen in radix console all together. It is not a big issue, but separator is missing here so it looks like one long word/link.

Screenshot:

![image](https://user-images.githubusercontent.com/6915328/61777783-d1d15980-adfd-11e9-8898-253032a5f3bc.png)

**Comment by dbelyaev** [comment]
Should look like this:

![image](https://user-images.githubusercontent.com/6915328/61778235-a733d080-adfe-11e9-9754-7912a3c42b12.png)

**Comment by emirgens** [comment]
Thanks for reporting!
We have registered this as a bug, and added to our backlog. Sooner or later you'll see that it has been fixed.....

https://equinor.atlassian.net/browse/RA-551

**Comment by nemzes** [comment]
Fixed in 3.2.0
