### ISSUE TITLE
Add environment variable showing latest commit hash from git

### ISSUE THREAD

**Issue by hermanjakobsen** [equinor/radix-platform#181]
Could it be possible to implement a new environment variable (which is automatically added by `Radix`) which shows the latest commit hash from Git? Right now I have solved the issue by adding a component `webapp` which shows this kind of information, but this solution seems unnecessary complicated. 
The app is https://console.playground.radix.equinor.com/applications/appoint

**Comment by emirgens** [comment]
We have registered this as a request in our Product Backlog, it will now be evaluated and prioritised.
This issue will be updated when fixed.
Ref.: https://equinor.atlassian.net/browse/RA-552

**Comment by ingeknudsen** [comment]
This has now been delivered. Environment variable is called:
- RADIX_GIT_COMMIT_HASH
