### ISSUE TITLE
Be able to build images with local base image in repository

### ISSUE THREAD

**Issue by simentha** [equinor/radix-platform#188]
I have a Docker-image in the root directory of the repository, which some images further down in the folder hierarchy uses as base image. I tried to build this image as a component on Radix and hoped that the child images could pull the image from this component, but this did not work. Would be nice if one could use this "local" base image on Radix, and make the components be able to pull it from there. 

Application name in Radix: 
appoint

Cluster: 
playground

**Comment by emirgens** [comment]
Thanks for reporting! I've added it to our Product Backlog. It will be evaluated and prioritised.

Ref: https://equinor.atlassian.net/browse/RA-570

**Comment by emirgens** [comment]
This feature request have been evaluated by the Radix team and Product owner, and it has been decided NOT to offer this.
