### ISSUE TITLE
Parallel builds of similar components

### ISSUE THREAD

**Issue by SindreEquinor** [equinor/radix-platform#192]
Thanks for taking the time to report an issue or feature request.

If applicable, please provide the following information:

Application name in Radix: 
surface-api

Application component: 
all but proxy

Cluster: 
prod-1

Description:
The way this api is set up, all the backend components are essentially the same, they utilize the same image, but with different settings to serve different data sets. As these components all point to the same subfolder to locate the dockerfile it would be more resource efficient on the job side if the build was only done once rather than 7 times in parallel.

This in conjunction with #162 could massively simplify and speed up the deployment for large distributed applications.

**Comment by emirgens** [comment]
We have now registered this in our backlog.
https://equinor.atlassian.net/browse/RA-574

**Comment by ingeknudsen** [comment]
This has now been delivered to production. See screenshot below for how this will appear in the pipeline:

![Screenshot 2019-12-10 at 13 22 20](https://user-images.githubusercontent.com/10051649/70529174-36444980-1b50-11ea-8a3c-ef034f62a1b6.png)
