### ISSUE TITLE
Component Restart

### ISSUE THREAD

**Issue by SindreEquinor** [equinor/radix-platform#193]
Thanks for taking the time to report an issue or feature request.

If applicable, please provide the following information:

Application name in Radix: 

Application component: 

Cluster: 

Description:
From an operations perspective I would want the ability to restart any particular component at will from the console (such as if a backend service outside of goes down or something similar). As some components might be more vulnerable to this sort of event the option to restart a component rather than triggering a new build/promotion for the entire environment would be preferable.

**Comment by emirgens** [comment]
We have now registered this in our Product Backlog. It will then be evaluated and prioritised.

Jira ref.: https://equinor.atlassian.net/browse/RA-578

**Comment by ingeknudsen** [comment]
We have now delivered a solution to this issue:

https://www.radix.equinor.com/guides/component-start-stop-restart/
