### ISSUE TITLE
Manually stop / cancel a running job

### ISSUE THREAD

**Issue by chiangs** [equinor/radix-platform#197]
I'd like the ability to stop/cancel a running job.

**Comment by emirgens** [comment]
Thanks for reporting. This feature is in our Product Backlog, but not ready to be started on yet. However it will be evaluated and prioritised in the near future.

Jira ref: https://equinor.atlassian.net/browse/RA-33

**Comment by keaaa** [comment]
Its is now possible to stop a running or queued job. Closing the issue
