### ISSUE TITLE
Disable https redirect

### ISSUE THREAD

**Issue by flyrev** [equinor/radix-platform#201]
It would be convenient to be able to disable the https redirect, if one wants to deploy something other than a web service.

Related: https://github.com/equinor/radix-platform/issues/200

**Comment by emirgens** [comment]
We have now registered this in our backlog, will be groomed and prioritised.

Jira ref: https://equinor.atlassian.net/browse/RA-666

**Comment by emirgens** [comment]
This feature request have been evaluated by the Radix team together with the Product owner, and it has been decided NOT to offer this.
