### ISSUE TITLE
console.radix.equinor.com reloads many times instead of giving "Unauthorized" message

### ISSUE THREAD

**Issue by niand** [equinor/radix-platform#202]
When accessing console.radix.equinor.com the page just reloads 20-30 times, until finally ending up with a message saying I can't log in. Presumably because I don't have access. This could probably be handled a bit more gracefully. :)

**Comment by nemzes** [comment]
Yes indeed it could! 😅

We are aware of the problem, but it's some… weird interaction with Azure, so it's not straightforward to fix. We'll re-evaluate priorities and see if this comes up for fixing soon.

Internal tracking issue: RA-142

**Comment by emirgens** [comment]
A new authentication method has been implemented, so you should not experience this again.
