### ISSUE TITLE
Adding new secret to `radixconfig.yaml` will cause GUI to show `Missing Secrets` error before they are deployed

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#213]
Adding new secret to `radixconfig.yaml` and pushing it to `master` branch will cause radix to show `Missing Secrets` error in GUI while those secrets are still to be deployed thus unavailable to set.

Steps to reproduce:

- add new secret to component
![image](https://user-images.githubusercontent.com/6915328/63835270-64be6000-c977-11e9-892a-7d2cfab10c54.png)
- push to master
- go to `radix` web-ui and check this component (you'll see `Missing Secrets` error)
![image](https://user-images.githubusercontent.com/6915328/63835340-8cadc380-c977-11e9-9bb4-c825891e1207.png)
- click on component and check that only old secrets are available and they are consistent (thus error is not correct?)
![image](https://user-images.githubusercontent.com/6915328/63835379-9c2d0c80-c977-11e9-8975-c859338890ee.png)

After the first successful deployment those secrets became available and thus the warning message is now correct.
![image](https://user-images.githubusercontent.com/6915328/63835442-bb2b9e80-c977-11e9-9270-287c2d0d47c4.png)

**Comment by ingeknudsen** [comment]
Registered as a bug in the Product backlog.
https://equinor.atlassian.net/browse/RA-753

**Comment by emirgens** [comment]
A fix to this issue has now been implemented
