### ISSUE TITLE
Save all button for secrets

### ISSUE THREAD

**Issue by SindreEquinor** [equinor/radix-platform#224]
Due to the increased possibility of making a mistake when repeatedly entering secrets to multiple components, especially when the secrets are repeated across components I would request that you enable us to apply a secret to all components that have a matching secret property in the application. I am essentially requesting a "save for all" button alongside the regular save button. This would drastically reduce the time needed as well as the the probability of making mistakes when entering secrets into large constellation type applications.

The surface-api is one such application with its, currently 25, back-end components requiring 3 secrets each for a grand total of 300 across all environments. Managing this, especially in the case of a redeploy, or a credential swap, is not maintainable and results in a long downtime. Having this shortcut feature for rapidly entering the necessary secrets would enable us to do a reset of the credentials in relatively short order, thus decreasing the downtime.

For us this is only going to get worse as we add more assets, increasing the constellation size.

We could also us the cli when it becomes available, but this would enable to do manual triage if necessary without the need to script it. It should also help with the initial setup for other applications that might have similar constraints and/or complexity. 

If applicable, please provide the following information:

Application name in Radix: 
surface-api

Application component: 
all*

Cluster: 
production

**Comment by keaaa** [comment]
We will not prioritise this, as it seems to be limited to a small set of applications, with special requirements. 

As I understand it, you have already worked around the issue by scripting the updating of secret using our API directly (https://api.radix.equinor.com/swaggerui/). This could also be extended to other similar issues
