### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by SindreEquinor** [equinor/radix-platform#225]
Due to the issues presented by managing a lot of secrets, as stated in #224, we would like for a cli to be made available so that we can script the application of secrets to the various components of our applications.

 Preferably we would also be able to use this cli to get a log dump from the various components of the applications we manage, so that the outputs can be analyzed if needed (This would be in addition to those that we get from application insights).

**Comment by emirgens** [comment]
This is already in our product backlog, ref: 
https://equinor.atlassian.net/browse/RA-197
It will be prioritised by the product owner.

**Comment by keaaa** [comment]
A first version of Radix CLI has been started on. Its main focus will be to support deploy only scenario, where teams uses other CI tools than the one provided by Radix but still deploy to Radix. 

It should meet your needs (setting secrets and get logs from running components)

**Comment by ingeknudsen** [comment]
radix-cli version 1.0 has been released
