### ISSUE TITLE
UI change for build-deploy jobs

### ISSUE THREAD

**Issue by SindreOsnes** [equinor/radix-platform#226]
As applications grow larger in terms of the number of components the current configuration of the overview when looking at a build-deploy job is less efficient than it could be. 

The way it is now it seems that it structured so that you get the overall run summary alongside the list of components at the top and the various steps below these. As the list of components grows larger it pushes the list of steps down ad out of the page.

Because of this stacking the overall summary on top of the list of steps and having the list of components alongside this "stack" might allow for a more compact an usable UI for larger applications without impacting the smaller applications whose layout would remain essentially the same.

**Comment by keaaa** [comment]
Have added a bug for this: https://equinor.atlassian.net/browse/RA-810

It does not have high priority, but will be fixed in between other stories

**Comment by emirgens** [comment]
Will add this as input to usability testing work going on now. And hence closing this issue
