### ISSUE TITLE
Persisting storage

### ISSUE THREAD

**Issue by ReedOnly** [equinor/radix-platform#237]
We have the following issue:
We want to deploy something to Radix that is able to persist storage between deploys.

In this specific problem, we want to be able to deploy our own Prometheus instance with persistent storage of metrics. We need this separate instance so that metrics are not shared with all Radix users.

Prometheus offers a few solution for remote storage:
https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

Unfortunately as of now it does not seem possible to use PostgreSQL is Azure which could have been the preferred solution.

Thanks for your help,
Kristian Reed
Software Innovation Bergen

**Comment by emirgens** [comment]
Radix will not support persistent storage. However we have a solution that may work for you, using a Private Link to an Azure resource "owned" by you. Contact us on Slack if this is something you may consider. Will close this
