### ISSUE TITLE
Retrieve images from other applications

### ISSUE THREAD

**Issue by ReedOnly** [equinor/radix-platform#244]
Application name in Radix:
https://console.playground.radix.equinor.com/applications/oneseismic-deploy/envs/dev/component/api

We would like to use Radix to deploy components from different Github repositories. As of now Radix do not have access to other private repos, so in order to do this we need one of three alternatives:

a) Push images directly to `radixdev.azurecr.io` in order to use them as components for our application

b) Let Radix be able to pull images from our own private container registry which we could push images to with our own CI

c) Create a custom tag to the images pushed by other Radix applications. As a beginning, `:latest` would be helpful so we always can pull the newest image from another app.

I think both a) and b) would be very useful for us, but as a workaround, c) will also fix our issue.

Regards,
Kristian Reed
Software Innovation Bergen

**Comment by keaaa** [comment]
We have landed on b) being the most secure / usable solution for Radix - and might also be used when we open up for deployment from other CI/CD tools. I have created a story for it:
https://equinor.atlassian.net/browse/RA-944

We'll notify you when we start on this

**Comment by keaaa** [comment]
we have started on this issue

**Comment by keaaa** [comment]
We have solved the issue with private image hubs during deployment. However @turesheim pointed out that it would be good to also have access to private image hubs during build time.  We'll investigate if this is possible using our current docker builder, and come back to you.

**Comment by keaaa** [comment]
Private image hubs: It now possible to reference image from private image hubs during deployment time. For more info, see https://www.radix.equinor.com/docs/reference-radix-config/#privateimagehubs

**Comment by keaaa** [comment]
I have created a separate Issue for accessing private image repository during build time (https://github.com/equinor/radix-platform/issues/280). Closing this issue
