### ISSUE TITLE
Bug: Component Restart does not behave as expected

### ISSUE THREAD

**Issue by SindreEquinor** [equinor/radix-platform#252]
Clicking on the Start, Stop and Restart buttons in the console does not have the intended effect of just starting, stopping and restarting that particular component. Every click also triggers a restart of all components. This leads to the following behavior pattern:

**STOP**: Stops currently selected component, but also restarts all other components that have not been stopped.

**START**: Starts currently selected component, but also restarts all other components that have not been stopped.

**RESTART**: Restarts currently selected component, but also restarts all other components that have not been stopped.

Expected behavior would be that the that the commands apply to that component only, not all others.

It appears that the commands introduce a change in the configuration as intended, but that the implementation of the changes is environment wide rather than component specific, i.e. it redeploys with the changed configuration.

If applicable, please provide the following information:

Application name in Radix: 
surface-api

Application component:
all

Cluster:
production

**Comment by keaaa** [comment]
We have fixed this and released to production. closing the issue
