### ISSUE TITLE
Publish the YAML schema for easy validation

### ISSUE THREAD

**Issue by flyrev** [equinor/radix-platform#265]
In order to reduce the chances of configuration mistakes, it would be awesome if the schema for the configuration file was available.

**Comment by emirgens** [comment]
Christian,
this is already a user story in our backlog, however it has not been prioritised for development yet.

I'll link this request to the User Story, hopefully we can start on this soon.

Ref: https://equinor.atlassian.net/browse/RA-130

**Comment by dbelyaev** [comment]
+1

**Comment by emirgens** [comment]
Our ref.: https://dev.azure.com/equinor/Radix/_workitems/edit/45826

**Comment by oyron** [comment]
This will be prioritized in one of the coming sprints

**Comment by nilsgstrabo** [comment]
The schema for radixconfig.yaml is available here [https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json](https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json)

Read more here: [Slack](https://equinor.slack.com/archives/C8U7XGGAJ/p1678203269854699)  and  [Radix docs](https://www.radix.equinor.com/references/reference-code-editor-integration/#visual-studio-code)
