### ISSUE TITLE
App list:  Application latest job "Latest: (time)" - wrong timing

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#267]
When the status is e.g.  "Latest: Succeeded ( 40 minutes ago)", the time is computed from the beginning of the job instead of when the status-change happened.  If the job takes 39 minutes, it should should start from 0 sec and not from 39 minutes

**Comment by emirgens** [comment]
We have added this requirement to our Product backlog. We cannot promise when we will start on development of this feature.

Ref: https://equinor.atlassian.net/browse/RA-1073

**Comment by keaaa** [comment]
This has been fixed and released - Job with status "Running" uses start_time to calc how long it has run, while Job with any other status uses end_time if this is available

**Comment by john-haugland** [comment]
Thanks!
