### ISSUE TITLE
Project administrator contact email

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#270]
In order to make it easier for the Radix team to get in contact with project administrators, either individually or overall for important messages, there could be a configuration option per project for a point of contact email address.

I'm thinking this should be a mandatory field when creating a project, but there might be GDPR implications/requirements that need to be considered.

**Comment by emirgens** [comment]
Suggestion in our Product Backlog:
https://equinor.atlassian.net/browse/RA-81
Will be start worked on when prioritised.

**Comment by keaaa** [comment]
This feature is now available in Radix. Its a mandatory field when creating a new application, and can also be updated in the Configuration part of an App (also for old applications)
