### ISSUE TITLE
Environment label in list of Jobs -- Even from running jobs

### ISSUE THREAD

**Issue by oysteijo** [equinor/radix-platform#271]
If there are several jobs running, it would be nice to see which environment that is building. The list is there and the environment is stated for Jobs that have completed successfully. However Jobs that are running have no indication of which environment it's building and deploying.
![list of running jobs](https://user-images.githubusercontent.com/4855341/69541101-a9629300-0f88-11ea-8916-59bb42745f8c.png)

**Comment by emirgens** [comment]
We have now added this to our Product backlog.

Ref: https://equinor.atlassian.net/browse/RA-1076

**Comment by olemoi** [comment]
This has now been implemented.
