### ISSUE TITLE
Radix integration with other Azure resources

### ISSUE THREAD

**Issue by niand** [equinor/radix-platform#272]
Marketing & Supply has several applications with sensitive data. To enhance the security level for this type of applications we would like to be able to integrate PaaS AppGateways/WAF's into the solution, and also communicate with back-end PaaS services via service endpoints instead of public endpoints.

The base requirement to achieve this, is most likely *vnet peering* between AKS and Omnia Standalone subscriptions. 

Here's a diagram showing the direction we would like to take this:

![snip2](https://user-images.githubusercontent.com/6833119/69548350-7b387f80-0f97-11ea-88ca-cc788a88f09d.PNG)

**Comment by keaaa** [comment]
We will investigate different solution for how to increase security between Radix and other Azure services owned by development teams, and come back to you with findings

**Comment by keaaa** [comment]
As we agreed the story will be split in two:

1. Enable access from Radix to managed services through private endpoints (Service endpoints or Private Links seems to be two possible solutions for this)
2. Single-tenant Radix clusters for MSS.  We'll discuss this with relevant stakeholders and come back

**Comment by emirgens** [comment]
Out ref.: https://equinor.atlassian.net/browse/RA-1156

**Comment by emirgens** [comment]
Duplicate of #291 
This issue will be solved by the same.
