### ISSUE TITLE
Web console - access token expiring is not reflected in app

### ISSUE THREAD

**Issue by Brynjulf** [equinor/radix-platform#284]
Whenever my access token expires in the web console, I am not prompted to reauthenticate, nor am I notified about it. This causes problems when i trigger requests to radix' API which silently fails without me knowing about it.

I had dev tools up by chance before my token expired and after and noticed that the request itself returned a 401 as seen in the picture below.

![Screenshot 2020-01-07 at 12 45 52](https://user-images.githubusercontent.com/6473221/71893456-08045a80-314c-11ea-9acf-5e7b1e36e6ed.png).

This tends to be a problem whenever i start the web console app, where I am met with an error page saying I am not authenticated because i went directly to `https://console.radix.equinor.com/applications` instead of `https://console.radix.equinor.com` first.

Application name in Radix: 
mad-rep-api-nodejs
Application component: 
redis

**Comment by ingeknudsen** [comment]
We think this has been fixed yesterday. Please let us know if it reoccurs
