### ISSUE TITLE
external alias documentation fix

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#288]
[https://www.radix.equinor.com/guides/external-alias/](https://www.radix.equinor.com/guides/external-alias/)

The last step says

>What’s next
Once the secrets are saved the custom aliases should start working. (The Web Console doesn’t presently report those domains.)

This should be updated to mention that it requires the environment to be redeployed, either through a rebuild or promotion (or you can add a deploy keys button :) )

**Comment by keaaa** [comment]
Thanks for the input, we will fix this as part of a list of small improvements to UI / docs
