### ISSUE TITLE
Radix hosted in Azure East Norway

### ISSUE THREAD

**Issue by keaaa** [equinor/radix-platform#290]
Create a strategy for how Radix should related to new data center in Azure East Norway. Involve other Omnia teams and users for input. If Radix should be setup in East Norway, we should provide a timeline on how we move forward

**Comment by keaaa** [comment]
We have tested creating a cluster i Norway East, and after some attempts it seems to be running fine. The plan is then to start creating our official dev cluster i Norway East. If this goes fine, and all the integration tests passes, we then plan to migrate playground cluster to this region, so that the application developers for applications needing to run in Norway East due to proximity of data can test out their applications there. 

Eventually we think the production cluster also should be migrated to the Norway East region, but that is well into the future we believe, based on input from Omnia core team and from @lars.kaare. We don’t think we should maintain two production clusters in two regions, for Norway East and North Europe. 

If you have any objections/opinions around the move to Norway East, please let us know.

**Comment by emirgens** [comment]
Our ref.: https://equinor.atlassian.net/browse/RA-1155
