### ISSUE TITLE
Radix with access to resources on Equinor internal network

### ISSUE THREAD

**Issue by keaaa** [equinor/radix-platform#291]
As part of the Move to cloud, several applications will move to Azure cloud but still require access to internal resources as DB, Compute, ++. Radix should be a valid option for these applications. 

DoD
Involve IT infrastructure and Omnia Solum team to identify what is possible and not. 
Create a roadmap for progress 
Perform a new Security assessment of new cluster. 
Setup a Radix cluster with access to internal resources.

**Comment by emirgens** [comment]
Our ref.: https://equinor.atlassian.net/browse/RA-96

**Comment by magnus-longva-bouvet** [comment]
Is there an ETA on this feature? Highly anticipated in my team.

**Comment by oyron** [comment]
We did an extensive work trying to implement this, but the complexity turned out to be too high. This work will not be resumed unless there is a significant change in the demand for this.
