### ISSUE TITLE
Applications with GPU requirements

### ISSUE THREAD

**Issue by keaaa** [equinor/radix-platform#292]
As part of Kubernetes and AKS its possible to specify GPU requirements for applications, as described https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/ and https://docs.microsoft.com/en-us/azure/aks/gpu-cluster

Investigate if it's possible to have GPU node pools where applications specifying GPU resources are scheduled. Applications with no GPU requirements should still use node pools without GPU (cheaper)

**Comment by john-haugland** [comment]
I am task manager for an internal project, where we need GPU resources for computation/update. We are moving software from Amazon to Azure and would prefer to use Radix for deployment of all components to simply the CI/CD pipeline and cost monitoring. The need is immediate due to time constrains on the project.

**Comment by emirgens** [comment]
https://dev.azure.com/Equinor/Radix/_workitems/edit/67190

**Comment by oyron** [comment]
@keaaa & @john-haugland - do you consider this solved with the introduction of GPU jobs (https://radix.equinor.com/guides/configure-jobs/) ?
Btw, sorry for the long response time :)

**Comment by keaaa** [comment]
For our need this is perfectly OK. I guess for other it would be required also for deployments, but this could be a separate story.

**Comment by oyron** [comment]
We consider this feature request to be solved. Closing the issue, but please contact us or raise a new issue if you would like to propose extenstions to this feature.
