### ISSUE TITLE
Deploy only - allow specifying component

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#318]
We've started using the new deploy-only feature in Radix where we use Github Actions to build & deploy our apps. However, as we've gone for a (sort-of) micro service architecture with multiple backend and frontend services working in parallell, it would be really good if we could not necessarily deploy the entire application, but being able to just deploy specific components.

This would both allow us to only deploy the changed component without interfering with the others, and reduce the amount of stress on the radix system (startup of backend services can be rather expensive resource wise). 

An ideal solution would be to keep the current deploy command in the Radix CLI, but add a separate command, e.g:
`rx deploy-component -a application -c frontend...`
This would satisfy both those who generally deploy all or nothing, and those of us who only wants to deploy a specific component. It could also be a flag on the current deploy command, but I feel like that can quickly become messy to maintain.

**Comment by keaaa** [comment]
Hi, thanks for your input - we've created a story in jira: https://equinor.atlassian.net/browse/RA-1370 and will come back to you when we start on it

**Comment by JoakimHagen** [comment]
We have started working on adding a component specification throughout the pipeline, internally.
