### ISSUE TITLE
413 Request too large even when request is under 100MB

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#333]
**Describe the bug**
On playground I got 413 Request too large when uploading 4MB data

**To Reproduce**

**Expected behavior**
It has been solved by Dafferianto Trinugroho and setting proxy-body-size in Nginx to 50MB

**Application name in Radix**
geospatial

**Application component**
main

**Cluster**
- [ ] Production EU
- [ ] Production US
- [X] Playground

**Additional context**
There is a relevant discussion on slack.

**Comment by emirgens** [comment]
Setting in nginx is max proxy payload size = 100 mb. so this should not be an issue any more, see documentation:
https://www.radix.equinor.com/docs/topic-runtime-env/#request-size
