### ISSUE TITLE
Visible indication that a deploy has failed

### ISSUE THREAD

**Issue by rwiker** [equinor/radix-platform#334]
On a couple of occasions I've seen that a new version has successfully built and (apparently) deployed, but further checking reveals that the old version is still running.

I believe that this may happen if the new version fails shortly after starting, and the supporting machinery will then leave the old version running.

It would be useful to have a clear indication that this has happened in the Radix console, either as an alert icon, or a status indication on the page for the specific application.

**Comment by emirgens** [comment]
Thanks for your feedback!
This has now been added to our backlog, ready to be groomed and prioritised.
Our ref: https://equinor.atlassian.net/browse/RA-1415

**Comment by olemoi** [comment]
Hi!

This has now been implemented on both the application and environment page of the web console. On the application page there is a alert icon next to the failing component. On the environment page there is a 'Outdated component' label next to the component.
