### ISSUE TITLE
Websocket ingress annotation interval 

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#337]
**Is your feature request related to a problem? Please describe.**
I need to be able to set the websocket disconnect interval in order to test and develop code that handle unreliably data streams. The websocketfriendly setting does not currently override the system default setting. Setting/unsetting it per application does not have an effect.  When fixing the issue it will be better to be able to configure the interval within a range (instead of having 60 min). 

**Describe the solution you'd like**
Configure the ingress annotation interval as a per application setting. Currently the global setting is overriding the local application setting. 

**Describe alternatives you've considered**
Manual global setting is possible, but this is not optimal nor possible when several applications want different intervals. A per-application setting should be used. 

**Additional context**

**Comment by emirgens** [comment]
Thanks for reporting this, we have now added this to our product backlog.

Our ref: https://equinor.atlassian.net/browse/RA-1490

**Comment by nilsgstrabo** [comment]
Closing issue. Wesocket disconnect issue is resolved by submitter.
