### ISSUE TITLE
Getting started tutorial.

### ISSUE THREAD

**Issue by gjersvik** [equinor/radix-platform#338]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when creating new new radix applications.

**Describe the solution you'd like**
A getting started tutorial that brings up an example radix application from creating repo to authenticated login. Even if I do not follow it step by step its a great reminder of the steps needed when you have not done it in a while. Or for the first time.

**Describe alternatives you've considered**
An example app or two that are maintain would also be of great help that I can steal and modify from. I knew there was that in the past but did not try them this time as there was no link from documentation and i suspect they are out of date.

**Additional context**
I do a lot of testing and playing around so i create a new radix app every 6 moths or so. Enough time too forget the details. And to this day I have never been able to just do it without having to beg the radix team for support.

**Comment by emirgens** [comment]
Thanks for reporting - we have now added this to our Product backlog 

Our ref.: https://equinor.atlassian.net/browse/RA-1491

**Comment by emirgens** [comment]
Thanks for this, we will update our Getting started documentation to make it much better.

I'll assign you to review our PR on this :-)

(This time feedback within 24 months.....)

**Comment by emirgens** [comment]
Ole Martin, we have restructured the "Getting Started" info, can you have a look and provide feedback?
https://www.radix.equinor.com/start/

**Comment by oyron** [comment]
Sorry for the slow response on this. The getting started info has been updated a few weeks ago. Will close the issue now, but please let us know if you have other comments related to this.
