### ISSUE TITLE
Needed assistance: Problem serving static web content with multiple images over HTTP/2 in Radix

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#348]
**Describe the bug**
A static web site with multiple images on page doesn't perform well on Radix. Seems to be an issue with http/2, as we tested with the old app hosted as an Azure web app. [This](https://github.com/ingeknudsen/iknu-webviz-static) is a repo that maybe could reproduce the issue, although real example even perform worse. I can help with recreating the issue. The real case is [here](https://github.com/equinor/dasha). The resolution was to direct to the old [Azure web app](https://github.com/equinor/dasha/blob/3d38450c385bc6f9dbd355f8d571973037c7f3b4/radixconfig.yaml#L46). This is not optimal, but is an ok work-around for a while. The theory is that is is related to the multiplexing in http/2, which causes the backend to struggle, due to the high number of images on the page.

**To Reproduce**
1. Register the app, in say playground
2. Try to hit the https://web-iknu-webviz-static-dev.playground.radix.equinor.com/webviz/sub_pages/inplace_thickness_6.html endpoint and see the network tab. Me and Dafferianto got poorer performance on our Macs on Statoild Approved, than the others. So I am not completely sure if the repo is fully testing the issues that we have for the real application, which involves a Asp.Net.Core backend serving content from a storage account.

**Comment by oyron** [comment]
@ingeknudsen - is this still an issue? Sorry for the long response time :)

**Comment by oyron** [comment]
Thanks for the update. Closing the issue.
