### ISSUE TITLE
Investigate dependencies to the name "master" for the initial/main branch

### ISSUE THREAD

**Issue by larskaare** [equinor/radix-platform#351]
**Is your feature request related to a problem? Please describe.**

There is a trend looking int racially-charged language in sw dev. One suggestion is to rename the **master** branch to something else (Example https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/). What would this mean to Radix  - how hardcoded is the **master**

**Describe the solution you'd like**
A short investigation and proposal for how Radix could support another default name than **master**

While we are at it - are there other obvious terms used by Radix we should look at? (Example: https://thenextweb.com/dd/2020/07/13/linux-kernel-will-no-longer-use-terms-blacklist-and-slave/)

**Comment by emirgens** [comment]
Our ref: https://equinor.atlassian.net/browse/RA-1621

**Comment by emirgens** [comment]
#371 Look at these together

**Comment by jonaspetersorensen** [comment]
Possible solution: Let the user set his default branch as part of the registration of the radix app.
Example:
In the web console, when user register name of app, wbs etc then radix could also ask for which branch they use as default branch. By default (popular word!) Radix could set this value to be either "main" or "master".

In other words, my suggestion is to add default branch name to app metadata.

**Comment by nilsgstrabo** [comment]
We have released a fix for this issue.
When registering a new application, use the field **Config Branch** to specify what branch Radix should read radixconfig.yaml from.
Changing the name of the Config Branch can be done in the application's **Configuration** page
[https://www.radix.equinor.com/guides/configure-an-app/#registering-the-application](https://www.radix.equinor.com/guides/configure-an-app/#registering-the-application)
