### ISSUE TITLE
Status badge

### ISSUE THREAD

**Issue by SindreOsnes** [equinor/radix-platform#354]
To better integrate the Radix CI/CD pipeline with the solutions it is building. I would like to have a status badge from Radix to indicate the current state e.g. like DevOps or Travis.

**Comment by ReedOnly** [comment]
Yes, would like to see status of the latest job, so we easily can see if it has been deployed! Possibly choose which environment the badge should display :smile:

**Comment by emirgens** [comment]
This is registered in our backlog, and will be done when prioritised.
Our ref: https://equinor.atlassian.net/browse/RA-21
Thanks for reporting and taking part in the Radix community :-)

**Comment by nilsgstrabo** [comment]
This feature is now implemented. Read the guide here: [https://github.com/equinor/radix-platform/issues/354](https://github.com/equinor/radix-platform/issues/354)
