### ISSUE TITLE
Support for resetting the machine user token

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/radix-platform#357]
**Is your feature request related to a problem? Please describe.**
When using radix, and Azure, I would like all aspects to be automated. This includes creating / resetting the machine user token, and then uploading it to Azure Key Vault.
Now this part is a manual process.

**Describe the solution you'd like**
An option or command in the CLI to reset (and/or possibly get) the machine user token.

For instance `rx set machine-user`.

**Describe alternatives you've considered**
The alternative I've used, is to do it manually, and then copying the token where necessary.

Later, I've been told that it is possible to use the API on api.equinor.com, but I have not tried it.

**Comment by emirgens** [comment]
Registered in our Product backlog.
https://equinor.atlassian.net/browse/RA-1909

**Comment by satr** [comment]
Implemented in [release v1.0.3](https://github.com/equinor/radix-cli/releases/tag/v1.0.3)
`rx set machine-user-token -a APP_NAME`
Returns new token as plain text
