### ISSUE TITLE
Expose cronjobs in Radix

### ISSUE THREAD

**Issue by keaaa** [equinor/radix-platform#362]
There are users that would like to schedule cron jobs in Radix. See https://equinor.slack.com/archives/C8U7XGGAJ/p1598864722000300

**Comment by emirgens** [comment]
Reference to Radix product backlog
[47137](https://dev.azure.com/Equinor/Radix/_workitems/edit/47137)

**Comment by oyron** [comment]
With the [jobs](https://radix.equinor.com/guides/configure-jobs/#configure-a-job) feature, the foundation is there to build a cronjob feature within each application, e.g. by using a scheduling library. We think this is better, than trying to build a generic cronjob feature that should fit different needs. Hence this will not be implemented
