### ISSUE TITLE
Allow for mounting Azure Storage Account blob containers to running components 

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#372]
**Is your feature request related to a problem? Please describe.**
I am working together with webviz team on finding a pattern for hosting webviz reports on Radix. We both see Radix as a perfect match because it is typically business users which are less proficient with cloud devlopment, who develop these reports. The issue with loading files from blob container inside the code is (as stated by the webviz team):

> ...see atm: (1) Microsoft Blob Python client appears to not natively support creating such a seekable Python byte stream connected to the blob store, i.e. you would have to download it all either to disk or in memory to work with further. This shoud still be an improvement scalablity wise compared to downloading files on demand without being able to safely delete them, but can give performance + space problems for single large files. (2) Some popular Python packages in Equinor like github.com/equinor/segyio are clever in the sense that they only read the bytes of a large SEG-Y file they need to, in order to do what the script is asking, but they currently only support taking in a path to file on disk (and not a seekable byte stream).

**Describe the solution you'd like**
https://public-site-radix-platform-blobfuse-flexvolume.radix.equinor.com/docs/reference-radix-config/#volumemounts

**Describe alternatives you've considered**
We have tried to load data from within the component in the generated webviz code. This is a viable option, but we see we may run into issues with this (as stated above). We see also we are not the only ones which would like this feature implemented (i.e. https://equinor.slack.com/archives/CBKM6N2JY/p1580112473016400)

**Additional context**
See linked PRs:
https://github.com/equinor/radix-flux/pull/125
https://github.com/equinor/radix-operator/pull/489
https://github.com/equinor/radix-api/pull/280
https://github.com/equinor/radix-platform/pull/373

**Comment by emirgens** [comment]
Torje, Øyvind

Pls. have a look at this. Let's discuss when you have had a look.

**Comment by satr** [comment]
Implemented
