### ISSUE TITLE
Different date formats in "COST" widgets on Radix web consoe

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#375]
### Describe the bug
`Cost estimate` and `Cost forecast` widgets available in Radix web console are using different date formats.

- cost estimate: `dd.mm.yyyy`
- cost forecast: `mm/dd/yyyy`

Those are usually seen together, looks like they should use the same date format for output.

### To Reproduce
1. open radix web console for an app with connected cost
2. check what cost widgets renders

### Expected behavior
Both widgets should use the same date format

### Screenshots
![image](https://user-images.githubusercontent.com/6915328/95848997-1f155000-0d4f-11eb-8665-243f04b80453.png)

### Application name in Radix
app name: **eims**
url: [Radix EIMS dashboard](https://console.radix.equinor.com/applications/eims)

### Cluster
- [X] Production

**Comment by nilsgstrabo** [comment]
We have fixed and released to production.
You may have to refresh browser cache to see the changes.

![image](https://user-images.githubusercontent.com/65334626/95867792-d4550180-0d69-11eb-8f55-4642d3bb4739.png)
