### ISSUE TITLE
www required in front of radix.equinor.com

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/radix-platform#377]
Semi-related to #63.

Visiting https://radix.equinor.com apparently does not work, you need the `www`, i.e. https://www.radix.equinor.com.

Chrome increases the confusion a bit, by removing `https://www.` when visiting https://www.radix.equinor.com, such that you _think_ you can write [radix.equinor.com](https://radix.equinor.com) next time you visit Radix in Firefox.

**Comment by emirgens** [comment]
We will try to fix this.

**Comment by emirgens** [comment]
Added to our Sprint

**Comment by mhorveqn** [comment]
Production public site is scheduled for a fix this week.
