### ISSUE TITLE
Parsing errors on radix config file

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#395]
**Is your feature request related to a problem? Please describe.**
When there is a spell error or missing keyword in the radix config file, it would be good to have feedback in order to correct the syntax. 

**Describe the solution you'd like**
When deploying a radix config, it would be good to have error reports on parts of the config that Radix is not able to use. 

**Describe alternatives you've considered**

**Additional context**

**Comment by emirgens** [comment]
Duplicate of #265 
These are probably almost the same thing, I'll close this.
