### ISSUE TITLE
Listing of automatically added environment variables for a component

### ISSUE THREAD

**Issue by joargr** [equinor/radix-platform#411]
**Describe the bug**
When listing the environment variables for a component the ones automatically added by Radix are specifically marked. If a user defined environment variable happens to have a name starting with `RADIX_` this will also be marked as automatically added.

**To Reproduce**
1. Add an environment variable for a component in `radixconfig.yaml` with a name starting with `RADIX_`
2. When the component is deployed, the listing of environment variables for the component will mark the variable as automatically added by Radix

**Expected behavior**
The user defined environment variable should not be marked as automatically added by Radix. Alternatively, the documentation for environment variables can have a note about automatically added environment variables having a `RADIX_` prefix, and a recommendation to avoid this prefix for user defined environment variables.

**Application name in Radix**
`rips-monitor-web`

**Application component**
`app`

**Cluster**
- [x] Production EU
- [ ] Playground

**Comment by emirgens** [comment]
Our ref: [101421](https://dev.azure.com/Equinor/Radix/_workitems/edit/101421)

**Comment by oyron** [comment]
Sorry for the long response time:) 
This was solved a while ago. Radix does no longer allow environment variables starting with "RADIX_". Closing the issue.
