### ISSUE TITLE
Add support to change Radix deploy key in a more easier way

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#413]
**Is your feature request related to a problem? Please describe.**
Due to security it is recommended to update/refresh deployment key once in a while with new values.
Repository responsible of Equinor GitHub company are getting notification mails about those routines:

> "According to `WR1211` governing document, keys and secrets should be reset yearly.
> The Deploy Key 'Radix Deploy Key' should have been updated `<AMOUNT-OF-DAYS>` days ago"

When logging to Radix dashboard there is no simple way to change\update keys.

**Describe the solution you'd like**
Click-click-done solution would be greatly appreciated!

**Describe alternatives you've considered**
n/a

**Additional context**
Original slack thread:
![image](https://user-images.githubusercontent.com/6915328/109620541-4ae87500-7b3a-11eb-8d46-2c03315097e5.png)

**Comment by emirgens** [comment]
#412 - duplicate

**Comment by emirgens** [comment]
Added to Product backlog

https://dev.azure.com/Equinor/Radix/_workitems/edit/78113

**Comment by audunsolemdal** [comment]
Small correction, WR1211 is a document you can find in docmap, not a <MACHINE-NAME>

**Comment by dbelyaev** [comment]
> Small correction, WR1211 is a document you can find in docmap, not a 'MACHINE-NAME'

Yes, you are right WR1211 refers to Equinors security document not a machine name.

**Comment by emirgens** [comment]
Updated the original issue :-)

**Comment by satr** [comment]
Deploy key and secret can be regenerated now: "Radix console"/"Configuration"/"Deploy Key", hit the button "Regenerate deploy key and webhook secret"
