### ISSUE TITLE
Provide RADIX_GIT_COMMIT_HASH as a build argument

### ISSUE THREAD

**Issue by trylle** [equinor/radix-platform#416]
**Is your feature request related to a problem? Please describe.**
We have tried to add `RADIX_GIT_COMMIT_HASH` to our applications. Our webpack app reads this during the build/bundling phase, but Radix currently only delivers this as an environment variable to a started container, which is too late for us.

**Describe the solution you'd like**
`RADIX_GIT_COMMIT_HASH` should (also) be provided as a build argument, similar to build secrets.

**Describe alternatives you've considered**
We could rewrite our code to use the hash from container start-up, but this seems like a very roundabout approach. It seems more natural to this humble developer that the hash is incorporated into the actual build. This approach means that Radix wouldn't need to keep track of which commit was used for each image, and would avoid the potential risk of mixing up what image has been used and what hash was delivered to the container (i.e. the app could potentially be running one image and reporting different/incorrect hashes).

**Comment by satr** [comment]
Registered as story [82083](https://dev.azure.com/Equinor/Radix/_workitems/edit/82083)

**Comment by magnus-longva-bouvet** [comment]
Implemented and rolled out
