### ISSUE TITLE
rx trying to use expired refresh token?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/radix-platform#423]
It looks like `rx` will try to use an expired refresh token?

How to (probably) reproduce:
1) Log in with `rx`.
2) Don't use `rx` for 90+ days.
3) Try to use `rx` again then gives something like:

> Failed to acquire a token: refreshing the expired token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on XXXXXXXXXXXXXXXXXXXX and was inactive for 90.00:00:00. 

The only way I could find to force `rx` to do a clean login was to `rm -rf ~/.radix` first.

Semi-related to equinor/radix-cli#20.

**Comment by emirgens** [comment]
Added as bug in our Product Backlog.

Our ref.: https://dev.azure.com/Equinor/Radix/_workitems/edit/90694

**Comment by oyron** [comment]
Sorry for the long response time:)
With the introduction of `rx login`, there is no longer a need for deleting `.radix` to force a clean login. Closing the issue, but please let us know if you run into similar issues.
