### ISSUE TITLE
As a developer I would like to be notified on Slack whenever a build fails on Radix so that I can take immediate action

### ISSUE THREAD

**Issue by nilsml** [equinor/radix-platform#424]
**Is your feature request related to a problem? Please describe.**
Sometimes the build is failing on Radix for whatever reason. In these situations the team is not notified, and thinks that all went well. Then we end up with an old version of the app being published, and at the same time we believe it is the most recent version of the app that is published. One has to manually check the dashboard to catch these kinds of issues.

**Describe the solution you'd like**
For Github actions we have Slack integrations so that the team get notified whenever something fails. We would like to have similar functionality for Radix. At least we want to get notified in a specified channel when something is failing. There might also be cases where you want to be notified when a new version is published/made active.

**Describe alternatives you've considered**
We tried setting up the existing Radix bot, but it does not seem to give us the functionality we want.

**Additional context**
Our application: https://console.radix.equinor.com/applications/energyvision

**Comment by emirgens** [comment]
We are working on something in the same direction as what you are requesting, however not exactly. Can this be a first iteration for you?

https://github.com/equinor/radix-platform/issues/354#issue-680227002

In short the solution will be a badge "url" for each app, which will provide the status of the last build/deploy.

Not implemented yet.

**Comment by nilsml** [comment]
I guess a badge is better than current solution, but it still requires that the team actively check GH for the status. What we need is a way to be notified immediately if something fails. Slack is the preferred communication channel for this as this is being used for all other CI-related messages. A browser notification could be another alternative.

**Comment by emirgens** [comment]
We will add this request to our Product backlog, it will then be evaluated for priority.

Our ref: https://dev.azure.com/Equinor/Radix/_workitems/edit/90567

**Comment by nilsgstrabo** [comment]
We have released a new feature for sending alerts to Slack whenever a pipeline job fails or a component or job fails to start or crashes/restarts.
Please read the [documentation](https://www.radix.equinor.com/guides/alerting/) on how to configure alerting in Radix.
