### ISSUE TITLE
Add read-only access functionality to Radix web console

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#425]
**Is your feature request related to a problem? Please describe.**
Our testers need to have access Radix dashboards to check that deployment went well and nothing is crashed or throwing a lot of exceptions (ie components statuses and specific components logs). It is crucial for testing some maintenance deployments (when there is no code changes or only infrastructure updates has been done, like more memory to components etc).

**Describe the solution you'd like**
For us it could work via assigning additional fg group with tester users to something like "Read only access" configuration in Radix. 

**Describe alternatives you've considered**
We consider moving those maintenance tests to developers that have access but this will be wrong as testers should test and verify those. 

**Additional context**
Testers usually do not need to have start/stop/restart functionality or want to avoid having possibilities to destroy something in environments (especially production) by simply clicking wrong place.

**Comment by jonaspetersorensen** [comment]
A possible side track is to expose that kind of information in the app specific dashboards in Grafana.
Today Radix expose default metrics (cpu, memory etc) in Grafana, where each app has its own dashboard. My thinking is that deployment metrics could also be part of the default metrics.

This ofc would not give access to container logs, but at least it makes it possible for app users to see what it going on with their deployments over time.

**Comment by dbelyaev** [comment]
Grafana adds another layer of knowledge needed for test users to just check vital statuses on deployment and makes it more complicated for them.

**Comment by emirgens** [comment]
In general this mean to add a new role to "Role based access".
We have added this to our backlog, and assigned the POs
Our ref: https://dev.azure.com/Equinor/Radix/_workitems/edit/93884

**Comment by oyron** [comment]
@SindreOsnes - has proposed introducing multiple levels of access to the Radix console:

- Admin - full access
- Contributor - access to logs, promotion, start/stop, but no access to the Configuration
- Reader - ready only access to Environments, Pipeline Jobs, Deployments, no access to Configuration

**Comment by oyron** [comment]
A few teams have requested variants of this feature, but we have not seen enough interest in this issue for this to be prioritized at this point (among all the other stuff on the backlog). Will keep the issue open for now.

**Comment by oyron** [comment]
As we have not received any new requests for this feature for the past 10 months, we are close this issue.
