### ISSUE TITLE
(feature req) Outgoing webhooks (90567)

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#429]
**Is your feature request related to a problem? Please describe.**
It would be very helpful if radix could support outgoing webhooks, that we could use to trigger pipelines (github actions, bots etc). E.g, often the people starting a deploy-job are not the same people who will test. Having outgoing webhooks would alleviate this, as we could then send a message in slack / send emails / start a new automation etc. 

**Describe the solution you'd like**
On:
  - Successful jobs
  - Failed jobs
  - Crashes

I would radix to enable outgoing webhooks, with a pretty basic payload, similar to:
```
{
  "app": "app-name",
  "env": "prod", // or null
  "component": "frontend", // or null
  "state": "COMPONENT_FAILURE" // or JOB_SUCCESS, JOB_FAILED
}
```

While this wouldnt cover *all* scenarios, it would be a good start (imo).

**Comment by yusijs** [comment]
Relates to e.g https://github.com/equinor/radix-platform/issues/424

**Comment by emirgens** [comment]
Added to existing US in backlog
https://dev.azure.com/Equinor/Radix/_workitems/edit/90567

**Comment by nilsgstrabo** [comment]
We have released a new feature for sending alerts to Slack whenever a pipeline job fails or a component or job fails to start or crashes/restarts.
Please read the [documentation](https://www.radix.equinor.com/guides/alerting/) on how to configure alerting in Radix.
