### ISSUE TITLE
Radix job resource specified by payload

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#438]
**Is your feature request related to a problem? Please describe.**
Specify job resource by payload

**Describe the solution you'd like**
Job resource is able to be dynamically set by job payload. e.g. a large model simulation can request more CPU determined by a frontend app

**Describe alternatives you've considered**
Currently we plan to have multiple jobs in the config for low, mid, high CPU load

**Comment by emirgens** [comment]
This has been added to Radix product backlog and will be up for evaluation and prioritization

Our ref: [100665](https://dev.azure.com/Equinor/Radix/_workitems/edit/100665)

**Comment by emirgens** [comment]
This has now been fixed.
