### ISSUE TITLE
Support for Azure Key Vault for Radix secrets

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#439]
**Is your feature request related to a problem? Please describe.**
It is a hassle to setup if the app has multiple secrets or if the same secret is used by multiple components

**Describe the solution you'd like**
Only specify an Azure key vault secret in Radix. Then radix will fetch all the relevant secret base on secret name saved on key vault. It is easier to rotate tokens as there will be one single source of truth
Similar to https://github.com/marketplace/actions/azure-key-vault-get-secrets

**Describe alternatives you've considered**
Use the experimental radix CLI for Github action https://github.com/equinor/radix-github-actions

**Comment by ingeknudsen** [comment]
Could possibly be solved using this:
https://github.com/Azure/secrets-store-csi-driver-provider-azure

**Comment by emirgens** [comment]
Added to our Product Backlog
Our ref: [104262](https://dev.azure.com/Equinor/Radix/_workitems/edit/104262)

**Comment by oyron** [comment]
We have now started on implementing this.

**Comment by satr** [comment]
Implemented.
https://www.radix.equinor.com/references/reference-radix-config/#secretrefs
