### ISSUE TITLE
Regular security scans of built Radix applications

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/radix-platform#445]
**Is your feature request related to a problem? Please describe.**
There is now a security scan in Radix at build time. If you are unlucky, a critical vulnerability can be discovered/made public hours after build time without you knowing.

**Describe the solution you'd like**
I would like Radix to regularly scan also existing built applications, and notify app owner (e.g. by email to Radix owner-mail).

**Comment by emirgens** [comment]
This is in our backlog, we will also look at your additional info when evaluating the user story.
Our ref.: [47162](https://dev.azure.com/Equinor/Radix/_workitems/edit/47162)

**Comment by emirgens** [comment]
This is now implemented
https://www.radix.equinor.com/docs/topic-vulnerabilities/#scheduled-scan-of-deployed-images
Closing this request.
