### ISSUE TITLE
Job api: Log from component that start the job

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#453]
**Describe the bug**
For the active jobs, we need log from the component that starts the job to resolve startup problems. 

**To Reproduce**
Schedule a a job with payload as POST message with problematic json content. 

**Expected behavior**
The log from the scheduled job should contain log from the component that starts the job. 

**Screenshots**

**Application name in Radix**
dipvp

**Application component**
job-medium

**Cluster**
- Playground

**Additional context**

**Comment by emirgens** [comment]
We have added this to our Product backlog ready to be evaluated
Our ref: [101715](https://dev.azure.com/Equinor/Radix/_workitems/edit/101715)

**Comment by oyron** [comment]
This will be included in job management review. See my comment on #458

**Comment by oyron** [comment]
We have decided to implement this

**Comment by satr** [comment]
Added job-scheduler log to a job component form

**Comment by oyron** [comment]
This item has now been implemented. Let us know if it does not work as expected. Closing the issue
