### ISSUE TITLE
job api: Maximum run time from job payload

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#457]
**Is your feature request related to a problem? Please describe.**
If job component does not finalize within reasonable time, it should be killed. 

**Describe the solution you'd like**
Define maximum run-time in the payload. If not existing, use default value, e.g. 24 hours.

**Comment by emirgens** [comment]
This has been added to our Product Backlog, and will be evaluated and prioritised.
Our ref: [104246](https://dev.azure.com/Equinor/Radix/_workitems/edit/104246)
