### ISSUE TITLE
jobs: Admin overview

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#458]
**Is your feature request related to a problem? Please describe.**
Console to contain a better job overview. Show jobs as a table with run state (started, running, stopped, failed etc), run time and columns with payload string type parameters. Possibility to terminate running jobs.  Maybe combine the overview from different job components to list all jobs for a deployemnt in one table.  Possibility to sort table on column names. 

**Describe the solution you'd like**
Implement in the radix console when clicking on a job component.

**Comment by emirgens** [comment]
We are planning a redesign of the Web console (incorporate EDS), and will take your suggestion into account. I'll add it to the plan for Web console re-design. 
Our ref: [104250](https://dev.azure.com/Equinor/Radix/_workitems/edit/104250)

**Comment by oyron** [comment]
We have discussed this and decided that this will be prioritized for implementation in one of the upcoming sprints.

**Comment by oyron** [comment]
We have decided to implement the following improvements to job management in Radix:

- Sort job tables on column names
- Display of job parameters
- Implement a stop (but not delete) feature

These items are but on our backlog and will be implemented within the coming sprints

**Comment by oyron** [comment]
We have implemented sorting in tables and display of job parameters. Implement a stop, but not delete feature is in progress, and is covered by issue #459. This issue will now be closed.
