### ISSUE TITLE
Show (deleted) job in console - add delete button

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#459]
**Is your feature request related to a problem? Please describe.**
Deleted jobs are removed from console page

**Describe the solution you'd like**
Show deleted jobs in console with status 'Deleted'

- [x] Task 1
- [ ] Task 2

**Comment by emirgens** [comment]
Added to our backlog for evaluation
Our ref.: [104256](https://dev.azure.com/Equinor/Radix/_workitems/edit/104256)

**Comment by oyron** [comment]
@adamchengtkc - Could you please elaborate on the need / use case for this. 
Conseptually, I think it makes sense that a job is removed and no longer visible after deletion. Otherwise, "delete" would mean to set it to a "deleted" state, but still keeping it. Then you would probably need a "remove" action as well.

**Comment by adamchengtkc** [comment]
I think what you have described make sense as a job is deleted. But at the same time Radix doesn't have a cancelled status for a job. If a job is manually cancelled by a user (aka deleted) there is no trace of it for the dev. May be it needs to implement a cancel state in addition to a deleted state

**Comment by oyron** [comment]
We see that there are room for improvements on job management, and will review all proposed job mgmt improvements, including the ability to stop jobs without deleting them, and decide on what to implement. Will get back to you with an update.

**Comment by oyron** [comment]
We have decided to implement functionality for stopping (but not deleting) jobs. This has been placed on our backlog and will be implemented in an upcoming sprints (it might take a while, as we have much in queue)

**Comment by oyron** [comment]
This work is now ongoing. We expect to release this within a few weeks.

**Comment by oyron** [comment]
A stop button in web console as proposed in #847 will be part of the ongoing implementation.

**Comment by oyron** [comment]
Distinction between stop and delete, including stop and delete buttons, are now implemented and deployed
