### ISSUE TITLE
add RADIX_GIT_COMMIT_TAG

### ISSUE THREAD

**Issue by cbuv** [equinor/radix-platform#460]
**Is your feature request related to a problem? Please describe.**
I wan't to quickly check version of the application is deployed in different environments. 
Current workflow is to check commit hash against releases in GitHub. 

**Describe the solution you'd like**
A radix environment variable similar to git commit hash: RADIX_GIT_COMMIT_TAG

**Describe alternatives you've considered**
Lookup GitHub tags

**Additional context**
Would also be beneficial to list tags on the overview page in radix console.

**Comment by oyron** [comment]
This was discussed in the Radix reference group meeting June 23rd. @cbuv also proposed the the git tag is visible in the dropdown when selecting which build to promote. I think this is a good idea, and would like the Radix team to assess the complexity of doing this @emirgens

**Comment by magnus-longva-bouvet** [comment]
A single git commit hash can point to multiple tags, so the RADIX_GIT_COMMIT_TAG environment variable would have to be an array. @cbuv is currently on leave, so discussed this issue with @jonasbjoralt. A satisfying implementation would be to make RADIX_GIT_COMMIT_TAGS be a space separated list of tags.

**Comment by magnus-longva-bouvet** [comment]
Rolled out in production on 16th of August
