### ISSUE TITLE
root docker for jobs shows as running

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#461]
**Describe the bug**
If runasnonroot is set and the docker image is root. Job will not start but console will show as running

**To Reproduce**

**Expected behavior**

**Screenshots**

**Application name in Radix**
If it is your application then add the name as registered in Radix.
If it is our application then add the name as it appears you (radix-console, radix-api etc).

**Application component**
If applicable, add the name of the specific component(s) that fail

**Cluster**
- [ ] Production EU
- [ ] Playground

**Additional context**

**Comment by emirgens** [comment]
Also added as Bug in our Product backlog

**Comment by satr** [comment]
Fixed
