### ISSUE TITLE
As Next.js user I need to be able to configure the metrics path because /metrics cannot be used

### ISSUE THREAD

**Issue by nilsml** [equinor/radix-platform#468]
**Is your feature request related to a problem? Please describe.**
A standard Next.js setup does not let you put any api endpoints at root, but rather under `/api`.
So `/api/metrics` is totally feasible. However this is not configurable in Radix atm.

**Describe the solution you'd like**
Possibility of configuring the url for the `metrics` endpoint in `radixconfig.yaml`.

**Describe alternatives you've considered**
We can spin up a custom Next.js server using express to get around the problem, but it is not ideal.

**Additional context**
Slack thread: https://equinor.slack.com/archives/CBKM6N2JY/p1629382594036400

**Comment by nilsml** [comment]
Any indication on when/if this will be done? As far as I know it is a quick fix, and would really be appreciated by the Energyvision project 😃

**Comment by emirgens** [comment]
Our ref: https://dev.azure.com/Equinor/Radix/_workitems/edit/115432

**Comment by nilsml** [comment]
Any updates on this @emirgens? :smiley:

**Comment by oyron** [comment]
@nilsml - this is included in the sprint starting on Monday

**Comment by Pespiri** [comment]
@nilsml This feature has now been implemented 😃 
Read more about it [here](https://radix.equinor.com/references/reference-radix-config/#monitoringconfig)
