### ISSUE TITLE
Separate build secrets

### ISSUE THREAD

**Issue by john-wennstrom** [equinor/radix-platform#476]
### Problem
We have a need to define `build secrets` unique for environments. We have a Dockerfile that reads build secrets and forwards them to `dotnet build` like this: `dotnet build "<Project>" -p:mocking=${MOCKING} -c Release  -o /app/build` 

In our dotnet project we have services that we want to scope to mocked services when we deploy to our testing environment, but when setting Radix build secret, it will be defined globally for all environments. That is not very convenient. 

### Solution
I would like a solution like this:
![1630663753618](https://user-images.githubusercontent.com/70199975/131990026-fe3c9ed3-5402-42bc-9a02-dc6aaf152d96.png)

### Alternative
We are using a less optimal solution, we use different Dockerfiles in our branches and ignore them in merges. It works, but is not convenient.

**Comment by oyron** [comment]
This will be implemented in one of the coming sprints

**Comment by emirgens** [comment]
Our ref [102332](https://dev.azure.com/Equinor/Radix/_workitems/edit/102332)
