### ISSUE TITLE
Add Dynatrace instrumentation to the production cluster

### ISSUE THREAD

**Issue by lightenup** [equinor/radix-platform#492]
We want to see data in Dynatrace for our apps in Radix. If we where to this ourselves we would need to instrument each and every app. It would be good  if this could be done centrally in the Radix cluster for all its apps.

**Comment by oyron** [comment]
We have started working with Kanari to see what the Dynatrace APM service can offer and how it can be implemented in Radix. Within the next few weeks we will know more on how this could look like.

**Comment by emirgens** [comment]
Our backlog ref: [Feature 111736](https://dev.azure.com/Equinor/Radix/_workitems/edit/111736)

**Comment by oyron** [comment]
The integration with Dynatrace was stopped in April, due to a number of technical issues. It is not likely that this work will be resumed. The issue will be closed, but keep in mind that you can always instrument your application yourself to Dynatrace.
