### ISSUE TITLE
SHA256 key for deployed images

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#515]
**Is your feature request related to a problem? Please describe.**
We have container images hosted in ghcr.io that are pulled down by radix deployment script. Currently we are not able to see the SHA256 key of the running pods. This is needed to check that the correct image is running. 

**Describe the solution you'd like**
Add the SHA256 key to the console.radix environment overview in addition to the name of the container.

**Comment by nilsgstrabo** [comment]
We have implemented and released this feature. Image digest for component replicas and jobs are available in the replica or job list.
