### ISSUE TITLE
List which IPs outgoing network traffic from Radix can have in web-console or/and cli

### ISSUE THREAD

**Issue by jonaspetersorensen** [equinor/radix-platform#527]
**Describe the solution you'd like**

Some users have external components where they want to filter incoming traffic.
Example: Allow traffic from radix and component B. Deny everything else.

Today we can get the IPs from Radix by running a query in Slack (slow), and possible later also find it the radix docs (might be outdated, also it is open if this ip info should have limited access).

In order to make the info 
- automatically updated
- limit access to info to radix users for security reasons

I suggest you make this info available in the radix api, which in turn can be extended to
- web-console for each environment (prod, playground, etc)
- radix-cli

Users can then use this info 
- in an automated way (api, cli), 
- manually verify it in the console (brainstorming/debugging/panic sessions), 
- and you have secured it behind radix login requirement to get it.

**Additional context**

Ref slack question from @kjellerik ,
https://equinor.slack.com/archives/CBKM6N2JY/p1633592048255300

**Comment by christertime** [comment]
+1 for this

**Comment by emirgens** [comment]
In progress

**Comment by oleterno-equinor** [comment]
A list of all possible IPs (active and inactive) for the cluster is now shown in the `about` section of the web console. We plan on adding the active IPs as an environment variable for all applications.

**Comment by oleterno-equinor** [comment]
The list of active cluster IPs have now been added as a Radix environment variable `RADIX_ACTIVE_CLUSTER_EGRESS_IPS` to all components.
