### ISSUE TITLE
job unique name available to container running the job

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#552]
**Is your feature request related to a problem? Please describe.**
I need access to the job unique name inside the container running the job

**Describe the solution you'd like**
Make the job unique name available as an environment variable to the container running the job

**Comment by nilsgstrabo** [comment]
A new environment variable, RADIX_JOB_NAME, is added to each job. This variable holds the name of the job, e.g. compute-20210407105556-rkwaibwe.
Read the [documentation](https://www.radix.equinor.com/guides/configure-jobs/#environment-variables) for a list of all variables added to a job.

**Comment by john-haugland** [comment]
Thanks! Very good.
