### ISSUE TITLE
Github action with machine user token can not be used with first time deployment of a new app

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#567]
**Describe the bug**
When registering a new app in the radix console, it is not possible to use github action to trigger the first deployment. (With machine token). It is possible to come around this problem by triggering a webhook deployement from github. After the first succeded pipeline job triggered by webhook, the github action trigger method also begin to work (unmodified). 

**Expected behavior**
First time deployement with Github action should also be possible.

**Comment by satr** [comment]
New registered Radix app can be build first time:
* Manually start a job
* Commit to the app repo, when github webhook is set
* Create a pipeline job by Radix CLI (with personal or machine user token): 
  `rx create job build-deploy -a radix-mini-app -b main --token-environment`
* Create a pipeline job by Radix CLI from github action (with personal or machine user token): [example](https://github.com/satr/radix-mini-app-with-github-action/blob/main/.github/workflows/build-push.yml)
![image](https://user-images.githubusercontent.com/702860/165911117-1826d2bf-0444-47ed-b739-cd7cbb758302.png)
