### ISSUE TITLE
radixconfig.yaml: Common env variables across env and maybe across components

### ISSUE THREAD

**Issue by kjellkongsvik** [equinor/radix-platform#58]
Hi,

We have to set various variables (e.g. AD tenant, client_id, authserver) that is common across envs and components. Many duplicates in radixconfig.yaml. Possible to avoid such duplicates?

Application name in Radix: complete

Application component: 

Cluster:

**Comment by SindreEquinor** [comment]
I would definitely like the across components functionality, it would simplify the radixconfig quite a bit. Also would like this feature for secrets.

**Comment by ingeknudsen** [comment]
Suggested solution:
https://github.com/equinor/radix-private/blob/master/maturing/RA-123-CommonEnvironmentVariables/index.md

**Comment by keaaa** [comment]
We'll start by introducing component env variables shared between env - see first part of @ingeknudsen document

**Comment by thezultimate** [comment]
This feature (common component environment variables) has been implemented and is deployed to production.
