### ISSUE TITLE
Security-measures for production-deployment

### ISSUE THREAD

**Issue by jonasbjoralt** [equinor/radix-platform#618]
**Is your feature request related to a problem? Please describe.**
Just as we review pull-requests to avoid a developer committing bad code to our main branch, we'd like a confirmation-step before deploying to our production-environment. That way, we'll avoid issues with accidentally deploying to production. 
Also, from a compliance-standpoint we want checks that no "rogue" developer pushes bad code into production. 

**Describe the solution you'd like**
 - Environments can be marked as protected 
 - To create a deployment here, a second person needs to confirm the deployment.

**Describe alternatives you've considered**
Create separate radix-application for our own feature-environments and sandboxes, and a second application which only builds from our main branch which we'll use for UAT and production.

**Comment by magnus-longva-bouvet** [comment]
Talked with @jonasbjoralt . Suggested a workaround by mapping the production Radix environment to a protected release branch in GitHub. Awaiting feedback from @jonasbjoralt team discussion

**Comment by jonasbjoralt** [comment]
The solution we landed on was to just have a separate sandbox app for our feature environment, since that saves us a bit of work maintaining a separate pipeline. Then our main app still only deploys from our main branch where everything is reviewed. 

Magnus' approach would also work and have more fine-grained control, but we though this way was easier.
