### ISSUE TITLE
As a DevOps person deploying to Radix I want to have an argument imageTag for the command rx create job so that we don't have to alter the radixconfig file for new versions

### ISSUE THREAD

**Issue by nilsml** [equinor/radix-platform#619]
**Is your feature request related to a problem? Please describe.**
It is hard to manage versions in a deploy-only regime since the radixconfig file needs to be modified by a script after each commit/build. We need a better solution that is less intrusive and brittle.

**Describe the solution you'd like**
Ref meetings with the Radix team and suggestion to have an argument imageTag  for the command rx create job.
This also needs to be available in the `equinor/radix-github-actions@master` action that we use for deploying to radix.

**Comment by nilsgstrabo** [comment]
We have an example repo that use a python script in a github action to modify imageTagName in radixconfig.yaml.

[https://github.com/equinor/radix-example-arm-template](https://github.com/equinor/radix-example-arm-template)

**Comment by oyron** [comment]
@nilsml - we have reconsidered and decided to implement support for providing image tag as a parameter from GitHub actions. We will report progress in #758.

**Comment by oyron** [comment]
Please discard the previous comment. A new issue #911 has been created for this. Progress will be reported there.
