### ISSUE TITLE
Enable ip-filtering on inbound traffic

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#628]
**Is your feature request related to a problem? Please describe.**
Some of our apps are only meant for internal users, and only meant to be consumed on equinors internal network. Currently the way for us to do this in radix is to add an ip-filter in an nginx-instance using the X-Forwarded header. However since the internal ips in the cluster can change, we need to accept forwarded ips from "everyone" (0.0.0.0).

**Describe the solution you'd like**
I want Radix apps to be configurable with ingress rules in a similar fashion as egress rules. Egress rules are currently supported, but ingress rules are not.

Easiest for end-users would probably be to have a predefined list of ips / ranges (e.g "All equinor", "Equinor - Norway" etc), but just being able to dump in a plaintext list of ips / ranges would be useful as well (e.g a list of allowed  or blocked ips / ranges)

**Comment by magnus-longva-bouvet** [comment]
Talked with @yusijs . Ingress rules which are configurable on Radix environment scopes in the radixconfig.yaml file would give sufficient granularity. Global scope would be more convenient.

**Comment by oyron** [comment]
Thank you for proposing this feature. We like the idea, but there is very few (if any) other other teams that have requested this feature. We also see that there has been little interest among Radix users to start using the outbound traffic ip filtering feature, which strengthen the impression that ip filtering is currently not something the Radix users are particularily interested in. This issue will now be closed. If more teams request this feature, we will reconsider.
