### ISSUE TITLE
Manual replica instantiation

### ISSUE THREAD

**Issue by ketilbrunequinor** [equinor/radix-platform#643]
**Is your feature request related to a problem? Please describe.**
Could be useful for doing manual scaling when required without the need for config.
If available through cli or an api could also be used to implement custom scaling

**Describe the solution you'd like**
A button for doing manual scaling to begin with. Could have some auto scale down rules included.
Even better would be cli or api command to add and remove replicas. This would allow customers to implement their own scaling rules based on arbitrary metrics.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by oyron** [comment]
We have decided to do spike on custom autoscaling rules, ref comment in #641 . The need for manual manipulation for testing/learing will be considered as part of that spike.

**Comment by oyron** [comment]
Closing this issue, reporting progress in #641

**Comment by emirgens** [comment]
- [ ] Add function for change # of replica in Radix CLI

**Comment by oyron** [comment]
We have decided to implement support for replica instansiation through Radix CLI

**Comment by satr** [comment]
- [ ] Support scale in radix-api
- [ ] Add scale command to Radix CLI

**Comment by oyron** [comment]
This feature is now implemented and deployed. Closing the issue.
