### ISSUE TITLE
Support k8s sidecar pattern

### ISSUE THREAD

**Issue by pettermk** [equinor/radix-platform#650]
**Is your feature request related to a problem? Please describe.**
Typically, for authn/authz we use a combination of tools, and we often use a dedicated proxy that can handle authentication or simple JWT validation. Usually we follow the concept of "trusted upstream" meaning that we expose the proxy on the internet to the user, and once a request has proper authentication we forward it to the trusted upstream service. Usually, when forwarding the request, the traffic is not encrypted and also often does not even require password authentication.

In modern development we should follow the concept of "zero trust", and the "trusted upstream" is now somewhere on the k8s network. Zero trust philosophy says there is not such thing as a trusted network. This means that compromised pods on the same network can access information easily by listening in on network traffic. Therefore encryption and credentials authentication is a good tool to reduce the blast radius of an attack. I believe putting the services on the same pod makes this unnecessary, at least the sidecar pattern is prevalent and commonplace in highly regarded products such as istio and dapr.

**Describe the solution you'd like**
Combining the proxy and the trusted upstream in the same pod means that the trusted upstream is on localhost, and as such not exposed to a k8s network. The details and illusions of abstraction here may be unclear, and the level of actual added security may be uncertain. The point is more to establish the good practices and developing conceptually around zero trust.

**Describe alternatives you've considered**
We can install the authentication proxy onto the trusted upstream image, but it is better to use the vendor provided docker image for a good separation of concerns, simpler build pipelines and shorter build times.

**Additional context**

**Comment by krsteen** [comment]
@pettermk @emirgens  We are also interested in this, as we would like to use Dapr in our solution :)

**Comment by oyron** [comment]
A generic support for the sidecar pattern will not be prioritized now. It is an interesting concept that probably will be considered when we are looking at a persistent logging solution. We are also doing an assessment of Dapr, which might require this. Closing the issue.
