### ISSUE TITLE
Azure key vault issue

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#652]
**Background of problem**
The use of Radix access to Azure key vaults was introduced to simply the maintenance of Radix deployed applications. With the currently developed solution it is possible to access several secrets from individual radix components and jobs. For each key vault that the component has access to, we currently need to provide two "secrets", the Client ID which is the client ID of the service principal that has access to the key vault, and the secret "Client secret".  The number of "secrets" we need to maintain is now two times the number of components plus two times the number of job schedulers (that need secrets). 

**Suggestion on how to resolve to problem**
The Client ID of the service principal is not a secret, and I would prefer to be able to define that in the Radix config file instead of manually entering it in the Radix console web-page.  This will make the number of secrets to maintain down to half the number. 
To avid repeated secrets in several components, I suggest introducing shared secrets for runtime environment, i.e., across components/jobs.  An alternative solution would be to support federated credentials. Service principals can be configured in Azure with "Kubernetes accessing Azure resource" (not beta anymore) to avoid the need for secret when accessing the key vault.  If this is configured, we can avoid providing secrets in the Radix console webpage. Each component needs to provide only the client id of the service principal with access to the key vault along with the azure subscription id and azure tenant id (all non-secrets) that could go into the radix config file.

**Comment by oyron** [comment]
Radix now supports federated credentials. Closing the issue.
