### ISSUE TITLE
Enable federated credentials

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#653]
I was curious if it would be possible for Radix to support federated credentials. Currently a lot of our projects are trying to move away from as much password-management as possible, but we will always need at least one for radix to access our private image hub in Azure. 

This was also suggested as a possible solution [in #652](https://github.com/equinor/radix-platform/issues/652), but I feel it deserves its own feature request. :)

Seems viable, given that azure supports it on kubernetes service accounts :) 
![image](https://user-images.githubusercontent.com/11261560/167403880-2a200280-bcea-46f5-9f8c-6c02013af770.png)

**Comment by emirgens** [comment]
Our backlog ref: https://dev.azure.com/equinor/Radix/_workitems/edit/185555

**Comment by oyron** [comment]
We have decided to implement this. The work will be started shortly.

**Comment by oyron** [comment]
This work has now been started. We expect to release this within a few weeks.
