### ISSUE TITLE
Support Service Principal for auth to mounting blob store

### ISSUE THREAD

**Issue by adamchengtkc** [equinor/radix-platform#654]
**Is your feature request related to a problem? Please describe.**
Currently, to mount a blob container requires account key. But the account key also has the power to do a lot of admin stuff.

**Describe the solution you'd like**
Authenitcate using Service Principal as stated in this example
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-auth.yaml

**Comment by emirgens** [comment]
Duplicate of #653

**Comment by adamchengtkc** [comment]
Hi, Thanks for looking into this issue. I think I am referring to service principal not federated credentials. This is already supported by the Blob CSI driver by setting `AzureStorageAuthType`. I am not sure there is a plan to support federated credentials in the CSI driver
