### ISSUE TITLE
DDoS protection

### ISSUE THREAD

**Issue by jonasbjoralt** [equinor/radix-platform#660]
**Is your feature request related to a problem? Please describe.**
Edited by oyron: Related to AlgoWall application. Downtime will have significant implications. Text moved to task board.

Describe the solution you'd like
Automatic detection of, and handling of DDoS attacks. (Azure DDoS-protection)

Describe alternatives you've considered
Detect spikes in traffic and make a manual action-plan to react to this kind of attack.

**Comment by emirgens** [comment]
We will come back to you on this subject.
