### ISSUE TITLE
deleting branch triggers a build-deploy job

### ISSUE THREAD

**Issue by nimsilva** [equinor/radix-platform#662]
I'm using short lived feature branches to deploy to one of the radix environments, whenever I delete this feature branch it triggers a build-deploy pipeline job with the commit hash 0000000: commit [0000000](https://github.com/equinor/esp-dashboard/commit/0000000000000000000000000000000000000000)
This job then fails on the Radix-pipeline and clone stages.

Error log of the Radix-pipeline stage:
time="2022-05-18T15:52:38Z" level=error msg="Failed to build application espdashboard. Error: Job failed. See log for more details"

Error log of the clone stage:
warning: Could not find remote branch releases/R1 to clone.
fatal: Remote branch releases/R1 not found in upstream origin

To reproduce:
1. Map a radix environment to a feature branch like: releases/*
2. Push releases/* branch to origin
3. Wait for radix to build and deploy
4. Delete the releases/* branch

- Production EU

Is this something I can mitigate?

Thank you :)

**Comment by emirgens** [comment]
We have implemented a fix which will solve your issue. Closing this now.
