### ISSUE TITLE
multiple radix applications for one github repo

### ISSUE THREAD

**Issue by siljehetl** [equinor/radix-platform#680]
Would it be possible to change functionality in radix to allow more than one application per repo ?

We want to have several applications in one mono repo. however they are not that dependent on each other, so it would make more sense if they could have been configured in several application with one radixconfig each.

We are planning to set it up with several components now, but based on that they are on the same network that might not be the most optimal solution.

**Comment by yusijs** [comment]
Would like to voice my support here as well for this; we have several apps that are "related but not really but kind of", would be cool if we could have 1 monorepo for those apps!

The biggest issue I can see with it for radix, is that the webhook would always trigger builds for everything (so if you have 10 apps in a monorepo and change 1, radix would build the other 9 as well since there is currently no cache mechanism built into radix).

**Comment by siljehetl** [comment]
@yusijs That is also how our setup is, one monorepo for several apps that are in related , but should be independent applications. To avoid that issue with building everything always, we have the build done by Github actions, where we specify which part of the monorepo to build. However, we still have only one application in Radix, which makes it a little less structure than we wanted ( and all the apps are also on same network when they are in one radix application..)

**Comment by yusijs** [comment]
Yes, we build via github actions as well, but the radix platform need to cover build as well, which is why I listed it as a possible blocker.. :)

**Comment by oyron** [comment]
Support the concept. We have started discussing alternatives and possible implementations, but not concluded yet. Aim for clarifying this in a refinement session next week.

**Comment by oyron** [comment]
This is now in queue for implementation

**Comment by emirgens** [comment]
For your information. We have now started the work on a feature to resolve this.

**Comment by satr** [comment]
This feature is implemented. 
Radix now supports:
* multiple Radix applications, having the same GitHub repository - monorepo strategy.
* custom Radix configuration file name (aka radixconfig.yaml) and its location in the GitHub repository
Please read more in the [monorepo guideline](https://www.radix.equinor.com/guides/monorepo/)
