### ISSUE TITLE
Option to display timestamps in the web console

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/radix-platform#689]
**Is your feature request related to a problem? Please describe.**
My application is crash-looping from time to time and having the timestamps in the web console would be very helpful for debugging.

**Describe the solution you'd like**
Have the timestamps in the web console as default OR a button that would allow me to toggle it on/off

**Describe alternatives you've considered**
A download button of the web console logs, where I could find the timestamps in a .txt

**Comment by emirgens** [comment]
Will this [new update](https://equinor.slack.com/archives/C8U7XGGAJ/p1656420683090219) to Radix platform solve **your** problem?

**Comment by fernandolucchesi** [comment]
> Will this [new update](https://equinor.slack.com/archives/C8U7XGGAJ/p1656420683090219) to Radix platform solve **your** problem?

The download option should fix it! Thanks! :)

**Comment by fernandolucchesi** [comment]
Hi @emirgens, unfortunately the download option does not include timestamps, so it did not fix it =(
