### ISSUE TITLE
cpu and gpu information for scheduled jobs console

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#698]
The console overview currently lists Image, Digest sha256 key, created, started, ended and duration. 

Can you include more information about the job ? 
* cpu limits and requests: memory and cpu
* gpu name and gpuCount
![2022-06-23_12-08-12](https://user-images.githubusercontent.com/25794638/175274979-c62138f3-64a8-445a-8bf5-2e052dd128fd.png)
t

**Comment by oyron** [comment]
Thank you for proposing this. We will look into introducing this for jobs and general components.

**Comment by oyron** [comment]
This feature has now been implemented and deployed.
