### ISSUE TITLE
Azure key-vault secrets in job components are sticky (not able to update)

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#699]
**Describe the bug**
A job scheduler with access to Azure key-vault for secrets does not update existing secrets from key vault. An expired secret that has been updated in Azure key-vault is not updated into a running job. 

**To Reproduce**
Try to update a secret in the Azure key-vault. The corresponing job in Radix that uses this secret is not updated when triggered. There is no way to update the secret other than contacting support and let them manually delete the current secret so that a new secret is downloaded. 

**Expected behavior**
Key-vault secrets in Radix job should be updated in job component when secret is updated in Azure key-vault, e.g. by refreshing the secrets automatically before each run.

**Comment by oyron** [comment]
@john-haugland - could you please verify if this is still an issue? The Radix team belive to have fixed this.

**Comment by john-haugland** [comment]
@oyron - yes, this issue has been fixed.

**Comment by oyron** [comment]
Thank you. Closing the issue.
