### ISSUE TITLE
As a developer I want to save some state in a datastore.

### ISSUE THREAD

**Issue by gjersvik** [equinor/radix-platform#72]
I would like Radix to have some kind of story around when you just need to store some state. I do understand why this is not a focus right now as creating stateless Platform as Service is hard enough. But soon-ish after the current PaaS is stable this would be very nice add on to radix.

Need a just works place to store my limited application state like with a reasonable expectation of availability and reliability.

I am not asking for a one size fits all data solution for all Equinors project as data management is hard. Just something simple when your needs are simple. Think something like Azure Sql 2GB.

I am not proposing what type of datastore/database i would like. If had anything more than personal preference I should not use what i propose you build.

PS. I do have access to some cloud subscriptions to store my state. But would like a just good enough simple solution as part of radix.

**Comment by satr** [comment]
Would [mount-volumes in Azure blobs](https://public-site-radix-platform-vp.dev.radix.equinor.com/guides/volume-mounts/) fit this need?
Another option (for relatively small values) maybe is to use Azure Redis
