### ISSUE TITLE
Using images from external registry in sub pipeline

### ISSUE THREAD

**Issue by FraaEquinor** [equinor/radix-platform#733]
**Is your feature request related to a problem? Please describe.**
We're using the deploy-only strategy in Radix in which we pull the images we require in Radix from a container registry outside of Radix. In that regard, we're experiencing a 401 issue on pulling an external image into our sub pipeline. It does not seem like the credentials using the regular radixconfig.yaml file is being used in the sub pipeline. Link to error message: https://console.radix.equinor.com/applications/wellcom-msa/jobs/radix-pipeline-20220829122034-x47eq/pipelineruns/radix-pipelinerun-dev-kzlmc-20220829122051-pqum2/tasks/view/radix-task-dev-kzlmc-refe-5t0i4-20220829122047-pqum2

**Describe the solution you'd like**
We would have liked to have the ability to use images from an external container registry in the sub pipeline by for instance implementing the ability to provide credentials for such a registry in the sub pipeline.

**Describe alternatives you've considered**
Our repository setup is a multi repository one and we would like to use the sub pipeline for running database migrations. As the code for database migrations is placed in a different repository than the Radix configuration file, having the database migration code together with the Radix configuration would entail a lot of restructuring of our setup.

In the meantime, we are handling database migrations manually instead of in the sub pipeline. However, this solution does not scale and is open for manual error and we would have liked to have database migration in place before our application goes live in the end of September.

**Additional context**
Slack discussion on the matter:
https://equinor.slack.com/archives/CBKM6N2JY/p1661779992456439

**Comment by emirgens** [comment]
Radix ref.: [257775](https://dev.azure.com/equinor/Radix/_workitems/edit/257775)

**Comment by FraaEquinor** [comment]
@emirgens Just checking in to see whether there has been any progress on this issue? :)

**Comment by FraaEquinor** [comment]
This issue has now been fixed as private registry credentials from the Radix configuration are now also available in the sub pipeline. This issue will therefore be closed.
