### ISSUE TITLE
Radix can't handle volume names longer than 64 characters

### ISSUE THREAD

**Issue by FraaEquinor** [equinor/radix-platform#735]
**Describe the bug**
There seems to be an issue with the key vault feature in Radix. Secrets from key vault are mounted in the replica, and the Kubernetes volume name is built by combining the component name and the key vault name. The max length of the name is 64 chars, which is exceeded in my case. The Radix team needs to fix this bug to handle volume names longer than 64 chars.

**To Reproduce**
1. Create a component utilizing an Azure Key vault reference with combined names that total more than 64 characters in length
2. The consequence of this change is that the component will be in the "Reconciling" state, however a log presenting the error is not visible in the Radix console. I learned about this error by contacting Radix support after my component had failed.

**Expected behavior**
The component should have been able to mount the volume with a name longer than 64 characters

**Application name in Radix**
Application: wellcom-msa

**Application component**
Component: reference-well-backend
At the time of writing, the Azure Key vault feature is no longer being utilised by the component while waiting for the bug to be fixed. The bug is therefore no longer present in the specified component and application.

**Cluster**
- [x] Production EU
- [ ] Playground

**Additional context**
Slack discussion on the issue: https://equinor.slack.com/archives/CBKM6N2JY/p1661758116659049

**Comment by nilsgstrabo** [comment]
Bug fixed. Closing issue.
