### ISSUE TITLE
Use machine user to view and edit buildsecrets in a pipeline

### ISSUE THREAD

**Issue by eiriksanderfjeld** [equinor/radix-platform#736]
I am unable to use a machine-user to update buildsecrets using the [Radix Api](http://api.radix.equinor.com/api/v1/applications/dcd/buildsecrets/dt_tenant). I get the following error message in return: 
`secrets "build-secrets" is forbidden: User "system:serviceaccount:dcd-app:dcd-machine-user" cannot get resource "secrets" in API group "" in the namespace "dcd-app`

I would like to be able to manipulate these secrets in the same way i manipulate component secrets with the machine-user.

**Comment by oyron** [comment]
We have discussed this. This will be implemented in one of the coming sprints.

**Comment by oyron** [comment]
Usage of machine user token is now deprecated in Radix. The support for it will be phased out in the coming months. Azure service principals or user-assigned managed identities can instead be used. Closing the issue.
