### ISSUE TITLE
Start/Stop/Restart functionality per environment

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#746]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to stop\start\restart all the underlying components in one specific environment, without going into each component consequentially and clicking the stop\start\restart buttons there.

**Describe the solution you'd like**
The same set of buttons that is now available per component (`Start` `Stop` `Restart`) should be made available per environment.
This should trigger start\stop\restart functionality the same way it does per component, but this time for all the components in the current environment (where those buttons are available).

**Describe alternatives you've considered**
I think the proposed solution is uniform with the existing functionality and will fit well enough.

**Additional context**

- Current implementation (only available per component):

![image](https://user-images.githubusercontent.com/6915328/190350582-5ae9eb27-2983-4241-9409-4083cd5be75a.png)

- After implementation (buttons are available per environment in addition to per components)

![image](https://user-images.githubusercontent.com/6915328/190350995-78579efc-3e15-4fae-8632-dedd07804c57.png)

**Comment by oyron** [comment]
We have evaluated this. Good proposal, this will be implemented in one of the coming iterations.

**Comment by emirgens** [comment]
Our ref: https://dev.azure.com/equinor/Radix/_workitems/edit/258869

**Comment by oyron** [comment]
This feature has been prioritized and will be implemented shortly.

**Comment by oyron** [comment]
This feature has now been implemented
