### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/radix-platform#747]
**Is your feature request related to a problem? Please describe.**
Equinor.com is a business critical application. It might happen, as it has happened on the incident of 30th August, that the website has a downtime due to different reasons (azure, radix, our own code etc). With the current default error page "503 Service Temporarily Unavailable" our users are not informed about what is happening.

**Describe the solution you'd like**
We would like to have a custom error page with support to anchor links, in order to direct our users to different communication channels (facebook/twitter/status page), where they will be able to find information about the downtime, minimising speculations.

**Describe alternatives you've considered**
Fallback DNS to another address when radix server responds with error.

**Additional context**
During the downtime we had, the [Equinor @ONS 2022](https://www.equinor.com/news-and-media/ons) event was happening, and journalists asked Equinor employees if we were under attack by Russian hackers 😅. We want to minimize as much as we can that such incidents affects Equinor's reputation, specially if such happens around Quarterly Results publications for investors.

**Comment by oyron** [comment]
We agree that this is an important feature. We will start looking into how this can be solved in the coming sprint.

**Comment by sondresjolyst** [comment]
Hello, we have now implemented a custom error page that will replace the nginx default error page "503 Service Temporarily Unavailable" on our clusters.

![image](https://user-images.githubusercontent.com/18713420/196347913-3fe5dbdf-8f9f-46cf-a424-22fd301e6dfa.png)

[Radix error page](https://github.com/equinor/radix-platform/blob/master/scripts/ingress-nginx/radix_error_page.html)

We can change this on the Equinor.com cluster to you guys liking. What we’ll need is a HTML file to serve when there is downtime.

Currently there are some limitations:
1.	CSS and JS need to be implemented inside the HTML file.
2.	Any photos or other files needs to be Base64 Encoded.

**Comment by SvSven** [comment]
Hi @sondresjolyst, we've now created a custom error page for the equinor.com cluster; the HTML for it can be found here: https://github.com/equinor/energyvision/blob/main/radix/error-page.html

Can you update this for us?

**Comment by sondresjolyst** [comment]
Hello @SvSven i have now added the error page to the equinor.com cluster 😉

**Comment by SvSven** [comment]
Perfect, thanks!
