### ISSUE TITLE
promote from environment

### ISSUE THREAD

**Issue by cbuv** [equinor/radix-platform#757]
**Is your feature request related to a problem? Please describe.**
Ensure that only code merged to main can be promoted to the production environment.
This problem occurs with a wildcard branch mapping setup.  (feature-*, feature/*)

**Describe the solution you'd like**
a new property "promoteFrom" in build config

**Describe alternatives you've considered**
current solution is to remove the wildcard mapping. 
another possible solution could use multiple radix application as discussed in #680 
 

**Additional context**
Our workflow is usually promotion as a manual step by having stakeholders signoff a release.

**Comment by oyron** [comment]
Have clarified with @cbuv that the wanted feature is `promoteFrom <environment>`

**Comment by oyron** [comment]
Have asked the Radix reference group for feedback on this.

**Comment by nilsml** [comment]
I think it could be a nice enhancement. In my team we mostly do deployments from GitHub Actions, so it will not have any impact on what we are doing.

**Comment by oyron** [comment]
We think this could be a somewhat useful feature, but after a brief discussion in the Radix reference group where the proposal did not get much clearly expressed support, we have decided not to prioritize this, as there are other features that are more important. Closing the issue, but will reconsider if more teams bring this up.
