### ISSUE TITLE
Configure liveness probe for component replicas

### ISSUE THREAD

**Issue by satr** [equinor/radix-platform#766]
**Is your feature request related to a problem? Please describe.**
[Readiness probe](https://radix.equinor.com/docs/topic-rollingupdate/#readiness-probe), configured in Radix out of the box for components has different parameters than [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). Having an configurable option of liveness probe, which designed to check on slow starting containers, can be beneficial for components, connecting to external services or databases.

**Describe the solution you'd like**
radixconfig.yaml has an option to configure liveness probe and its parameters for components and their environments

**Describe alternatives you've considered**
Dockerfile `CMD` can start with routine, awaiting initial startup, in parrallel providing stab-web-service, responding to readiness probe. Drawback - the stab-web service does not reflect actual component logic state. 

**Additional context**
It is not solved by InitContainer, as logic if initialisation is in the main container.

**Comment by emirgens** [comment]
Radix ref: https://dev.azure.com/equinor/Radix/_workitems/edit/263984

**Comment by oyron** [comment]
We will bring the topic of [Kubernetes lifecycle probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) up in the next reference group meeting, to get input on prioritization.

**Comment by pettermk** [comment]
I see I am _just_ too late on this, but I have a couple of reasons to enable readiness and liveness probes. We like to run various kinds of open source software on radix, these have helm charts we can use as starting points for setting up the Radix config in a way that the authors had intended it to be run. In our case, we like to run apache superset and trino, then it makes sense to setup readiness probes and liveness probes like their respective helm charts do, as so

https://github.com/trinodb/charts/blob/main/charts/trino/templates/deployment-coordinator.yaml#L90-L107
https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L308-L325

I recognize you have just made a decision on this so I don't expect any action, just leaving this comment for posterity.
