### ISSUE TITLE
Configurable readyness probe for component replicas

### ISSUE THREAD

**Issue by satr** [equinor/radix-platform#768]
**Is your feature request related to a problem? Please describe.**
Default readiness probe is configured in Radix component with first defined port and `TCPSocket`. In some services other validation methods and ports can be suitable.

**Describe the solution you'd like**
Radix `radixconfig.yaml` has an optional configuration option for altering readiness probe handler (`exec`, `http`,  `tcp`, `grpc`, with default `tcp`), port (from specified port list, with default first port), timeouts `initialDelaySeconds` and `periodSeconds`, `failureThreshold`

**Describe alternatives you've considered**
NA

**Comment by emirgens** [comment]
Our ref.: https://dev.azure.com/equinor/Radix/_workitems/edit/263986

**Comment by oyron** [comment]
Closing this as this is currently not requested by any teams. We will reconsider if teams start asking for this.
