### ISSUE TITLE
Make new version automatically manage config file (if needed)

### ISSUE THREAD

**Issue by satr** [equinor/radix-platform#775]
**Is your feature request related to a problem? Please describe.**
The tool has a dependency on a config file. Right now it is up to the user to keep this file in sync with tool version.

**Describe the solution you'd like**
Make the tool take ownership of sanity check and handling of that config file upon starting.

**Additional context**
Issue, moved from [radix-cli project issues](https://github.com/equinor/radix-cli/issues/25)

**Comment by oyron** [comment]
@satr - please elaborate on the idea, or close the issue if no longer relevant.

**Comment by jonaspetersorensen** [comment]
I can elaborate as I wrote the original issue.
Back then the user would update by simply replacing the bin file and do a manual update of any dependencies (configs etc).
If there is a mismatch between the tool and dependencies then they might not show up until the user is deep into a workflow, and even then the error messages could easily lead the user astray when debugging and so waste a lot of time.

The proposed solution is to make the cli tool do a sanity check of all dependencies upon start up and report any problems to the user right away. Or even better, provide suggested upgrades of the dependencies.

**Comment by satr** [comment]
Under dependency it is meant Radix CLI's `config` file, which need to be consistent

**Comment by oyron** [comment]
We are not aware that it is still common practice to manipulate the CLI config file. We have not got similar requests, and have decided not to prioritize this. If this at some point becomes an common issue, we will reconsider. Clsing the issue.
