### ISSUE TITLE
Show cert information and matching private key in the console

### ISSUE THREAD

**Issue by vnys** [equinor/radix-platform#780]
**Is your feature request related to a problem? Please describe.**
I uploaded the private key and cert files, but the browser refused to download the web page due to an invalid certificate. It turned out the problem was a newline character in the wrong place in the private key, possibly added by storing and then copying the key from LastPass. 

**Describe the solution you'd like**
In the documentation it would be nice if there was a paragraph about what you’re supposed to do _after_ you upload the private key and cert files to make debugging easier. I was under the impression that I needed to restart the application, which turned out to be false. It would also be nice if there was a paragraph about how to debug when something goes wrong. I got help from @magnus-longva-bouvet who discovered that the private key was corrupt, but I don’t know how he obtained that knowledge, or if that was something I could have done myself. If it was possible to show the cert and matching key in the Radix console I believe that would be helpful. This is something I do once or twice a year, so I have re-learn how to do it every time. Shortening the time that takes would be nice.

**Describe alternatives you've considered**
–

**Additional context**
–

**Comment by emirgens** [comment]
https://dev.azure.com/equinor/Radix/_workitems/edit/265873

**Comment by oyron** [comment]
Thank you for a good proposal, @vnys 👍 We believe this is solved now with the newly released certificate validation feature and the updated documentation: https://radix.equinor.com/guides/external-alias/#acquire-an-equinor-alias

**Comment by oyron** [comment]
Closing the issue now as this has been implemented, but please reach out if you have other concerns.
