### ISSUE TITLE
runAsNonRoot documentation is missing

### ISSUE THREAD

**Issue by dbelyaev** [equinor/radix-platform#785]
**Describe the bug**
It is not clear from documentation what `runAsNonRoot` does in radix config.  

More information link leads nowhere (same place?).  

Only a simple example with no explanation exist in documentation (link: https://www.radix.equinor.com/references/reference-radix-config/#runasnonroot).

> See [runAsNonRoot](https://www.radix.equinor.com/references/reference-radix-config/#runasnonroot) for a component for more information.

**To Reproduce**
1. open documentation link: https://www.radix.equinor.com/references/reference-radix-config/#runasnonroot

**Expected behavior**
Documentation should exist for this syntax entry?

**Screenshots**
![image](https://user-images.githubusercontent.com/6915328/197689299-9953ee60-9e5d-4825-b2f2-d3baba77bcde.png)

**Application name in Radix**
n/a (documentation)

**Application component**
n/a (documentation)

**Cluster**
n/a (documentation)

**Additional context**

**Comment by dbelyaev** [comment]
Not a bug but documentation issues. 
Should be a `docs` or `documentation` label`?

**Comment by dbelyaev** [comment]
@emirgens we still have it in our radixconfig (https://github.com/equinor/oilmod1-eims/blob/radix-config/radixconfig.yaml) from the time when it was required and used to test, if our containers will run smoothly. So, is it safe to remove those now? (as it is obsolete now)

**Comment by emirgens** [comment]
Yes it is. 
You will get an error if you try to build/deploy an app if not configured to run as NonRoot (in Dockerfile)

**Comment by oyron** [comment]
Documentation has been cleaned up. Closing the issue.
