### ISSUE TITLE
Allow manually specifying branch when creating new pipeline job

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#796]
**Is your feature request related to a problem? Please describe.**
The "New Pipeline Job" page in the Radix web console allows picking the predefined branch/environment targets from radixconfig. However sometimes it would be nice to build and deploy a specific branch to an environment There is also the case when you've configured a branch filter for an environment, then you can't start a job from the web console at all because the filter is not a branch name:
![image](https://user-images.githubusercontent.com/3266152/200585837-2a377960-3627-427b-8fbf-9d85560ed82b.png)
The example in the screenshot will fail since release/**/* is not a branch.

**Describe the solution you'd like**
The simplest solution would be to allow writing in a branch name manually and choosing a target environment. Probably a good idea to make it possible to lock an environment from being a manual target (for instance a prod environment).

**Describe alternatives you've considered**
Not sure to what extent you can get a list of branches from the github repo, if it is possible then populating dropdown based on the filter would solve the specific issue with branch filters.

**Comment by oyron** [comment]
Thank you for proposing this. This feature has now been implemented and deployed to Radix. Please reach out if you have other feedback/proposals.
