### ISSUE TITLE
App access policy restricted to Equinor employees only by default

### ISSUE THREAD

**Issue by anisayati** [equinor/radix-platform#800]
**Is your feature request related to a problem? Please describe.**
Radix will be used by non-expert web-app developers. There is always a risk that apps with sensitive information are deployed in Radix thinking that the app access is restricted to Equinor employes, whereas in reality it is not. Although it is surely documented in various places. 

**Describe the solution you'd like**
By default, the access policy of any app deployed in Radix (platform or playground) should be restricted to Equinor employees only. Then if there is a desire to open up the app to the world, the relevant steps should be taken. As of today, it is the other way around. 

**Describe alternatives you've considered**
Discussed with Sergey Smolnikov and Nils Stråbø on 11.11.22

**Additional context**

**Comment by oyron** [comment]
Thank you for submitting a feature request. It has always been the application teams' responsibility to implement access control and protecting against other cyber security threat vectors. The platform is not built to take care of this. We will however show an remider of this responsibility in the register new application dialogue.
