### ISSUE TITLE
Merge multiple radix.yml files into one

### ISSUE THREAD

**Issue by lmid76** [equinor/radix-platform#804]
Nice to have feature:

Would be nice if it could be possible to maintain radix config in different files. A dev.yml, test.yml and prod.yml that will be merged into one.

Since Radix is built on Kubernetes would it be possible to use this?

https://levelup.gitconnected.com/kubernetes-merge-multiple-yaml-into-one-e8844479a73a

**Comment by oyron** [comment]
Thank you for proposing this. We have discussed and decided not to implement. This is a nice to have, but we have other proposed features that we need to prioritize. You can look into YAML anchors as an alternative: https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/
