### ISSUE TITLE
Set nginx load balancing method from radixconfig.yml

### ISSUE THREAD

**Issue by HavardNJ** [equinor/radix-platform#82]
AFAIK the nginx load balancing between different replicas are round-robin by default. least-connected or ip-hash may be more relevant depending on application. It would be nice to be able to set this from radixconfig.yml

**Comment by ingeknudsen** [comment]
This have now been done. Note that we are not setting the load balancing methology directly, as this had issues on Kubernetes, but the new configuration should give you what you have asked for, we believe :)

See https://www.radix.equinor.com/docs/reference-radix-config/#ingressconfiguration for more information
