### ISSUE TITLE
Push notification on new Snyk vulnerabilities

### ISSUE THREAD

**Issue by aigelonic** [equinor/radix-platform#827]
**Is your feature request related to a problem? Please describe.**
Need to _manually_ go into the Radix console to inspect the Snyk-status on our built images.

**Describe the solution you'd like**
To get a (push) notification when new Snyk warnings arise. 
E.g. using the current "webhook"-approach to be configured to also include security related events (or a different webhook?).

**Describe alternatives you've considered**
Can setup our CI/CD pipeline to do the build of the image in GitHub Actions, only for scanning the final image with Snyk, but this is sub-optimal and one has not actually scanned the image that Radix builts and puts into the different environments.

Moving the building of image to GitHub Actions and pushing it to our own registry - again sub-optimal, as Radix provides this functionality "for free".

**Additional context**
NA

**Comment by emirgens** [comment]
We will include this in our refinement meeting, and may need to contact you for further clarifications.

Our ref: https://dev.azure.com/equinor/Radix/_workitems/edit/300761

**Comment by oyron** [comment]
Thank you for proposing this. We will include this in a planned review of our alerting/webhook functionality. We will come back to you with a status update when we have decided on the way forward.

**Comment by oyron** [comment]
We have looked into this. We see that this can be a useful feature, but it will require quite some effort, and we also see that there is a risk that this will be a noisy notification that teams will end up muting. We would probably have to implement a few filters/criterias to make this useful, which would make the implementation more complex. All-in-all there is little demand for this feature, but quite a bit of effort required. Hence we have decided to not prioritize this at this point. Closing the issue.

**Comment by aigelonic** [comment]
> @aigelonic - please update you GitHub profile with you full name, so we are able to reach out to you directly :)

Hmmm.. 
Unsure why, I have put my full name in the public settings of the profile 🤔 


Otherwise, sounds like you are finding the best long-term solution here 👍
