### ISSUE TITLE
Restart job on failures

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#833]
**Is your feature request related to a problem? Please describe.**
We would like to have an ability to set that a Radix job is automatically restarted if it fails unexpectedly. As stated in [this](https://equinor.slack.com/archives/CBKM6N2JY/p1647613931374949?thread_ts=1647612996.142349&cid=CBKM6N2JY) thread, there were plans to add `backoffLimit` to a job description, but I have yet to see this documented

**Describe the solution you'd like**
Add `backoffLimit` to job description. It would also be nice to have a restart mechanism when Radix performs cluster migration

**Describe alternatives you've considered**
We currently run jobs on Databricks, but want to migrate to Radix jobs. Databricks offers us the ability to restart the job if failure

**Comment by emirgens** [comment]
Our ref.: https://dev.azure.com/equinor/Radix/_workitems/edit/194338

**Comment by oyron** [comment]
What you propose is part of ongoing improvements to the jobs concept, and will soon be ready. Keeping the issue open for reporting progress.

**Comment by nilsgstrabo** [comment]
You can now control number of job restarts/retries via backoffLimit. This setting can be configured in [radixconfig.yaml](https://www.radix.equinor.com/references/reference-radix-config/#backofflimit) or by setting it when [creating a new job or batch](https://www.radix.equinor.com/guides/configure-jobs/#job-scheduler)
