### ISSUE TITLE
Custom name on a Radix job available in job listing of Radix console

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#834]
**Is your feature request related to a problem? Please describe.**
We have a set of applications we plan to run as Radix jobs on top of our platform. We would like a way to easily see that all applications we expect to have running are actually running. I.e. "WellboreA - Temperature Alarm". 

**Describe the solution you'd like**
We thought this would be another column, i.e. 'Custom Name'/ 'Description',  in listing of scheduled jobs, in addition to existing columns 'Name', 'Status', 'Created' and 'Duration' 

**Describe alternatives you've considered**
We could hold a mapping table listing applications and associated jobs

**Comment by emirgens** [comment]
Radix ref.: https://dev.azure.com/equinor/Radix/_workitems/edit/312485

**Comment by oyron** [comment]
This will be prioritized for implementation shortly.

**Comment by oyron** [comment]
This is now implemented and deployed.
