### ISSUE TITLE
Report back events of Radix jobs so that we don't need to continuously poll job status

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#835]
**Is your feature request related to a problem? Please describe.**
We plan to run applications on our platform as long running Radix jobs (possibly running for weeks), and we may want to act on changes to job running status. I.e. when jobs complete. 

**Describe the solution you'd like**
We could provide a webhook that Radix could use for callback

**Describe alternatives you've considered**
One alternative is to regularly poll status of jobs. Another alternative is that we make call to webhook from within the job, but there may be situations were job status change before job is able to report back to webhook.

**Comment by oyron** [comment]
Thank you for proposing this. We support the idea, and will include this in a planned review of our alerting/webhook functionality. We will come back to you with a status update when we have decided on the way forward.

**Comment by emirgens** [comment]
Radix ref.: [321743](https://dev.azure.com/equinor/Radix/_workitems/edit/321743)

**Comment by oyron** [comment]
This will be prioritized in one of the coming sprints

**Comment by satr** [comment]
- [ ] remove `radix-job-scheduler-server-main` and  `radix-job-scheduler-server-release` federated credentials from the SP `radix-github-workflows-dev`
- [ ] replace `radix-job-scheduler-server` with `radix-job-scheduler` in `radix-flux`
- [ ] release radix-operator, radix-job-scheduler, radix-tekton, radix-api, radix-web-console, radix-public-site
- [ ] remove `radix-job-scheduler-server` from `radix-acr-cleanup` list in `radix-flux`

**Comment by oyron** [comment]
This feature is now implemented, as announced on Slack. Closing the issue.
