### ISSUE TITLE
Radix batch job stop button

### ISSUE THREAD

**Issue by thezultimate** [equinor/radix-platform#847]
**Is your feature request related to a problem? Please describe.**
A batch job can run for a long period of time. Sometimes it is intended, but sometimes it is just a plain mistake in the code. It is quite difficult to stop/delete the batch job via the job-scheduler API because it is internal to the app, which means the app should include a feature to stop the batch job.

**Describe the solution you'd like**
A simple stop button on the Radix Web Console can be very useful.

**Comment by satr** [comment]
Extends the stop-job feature [in this issue](https://github.com/equinor/radix-platform/issues/459#issuecomment-1330275809)

**Comment by emirgens** [comment]
Radix ref.: https://dev.azure.com/equinor/Radix/_workitems/edit/102819

**Comment by oyron** [comment]
This will be implemented as part of ongoing work on #459. Status updates will be given in that issue, closing this.
