### ISSUE TITLE
Inconsistent use of casing in app names

### ISSUE THREAD

**Issue by AtleH** [equinor/radix-platform#85]
Radix requires app names created from the web console to be _exactly_ the same as in `radixconfig.yaml`. The web console enforces lowercase, but the `radixconfig.yaml` lets you write anything. I would suggest to either 1) not enfore lowercase in the web console, or 2) let radix be case-insensitive.

See Slack chat for details: https://equinor.slack.com/archives/CBKM6N2JY/p1550042550008900

**Comment by olemoi** [comment]
Lowercase names in the `radixconfig.yaml` file are now enforced. If a name containing uppercase letters is supplied, a warning is logged, and the name is converted to lowercase.
