### ISSUE TITLE
Create documentation for RADIX CLI

### ISSUE THREAD

**Issue by oyron** [equinor/radix-platform#863]
**Is your feature request related to a problem? Please describe.**
The Radix CLI lacks documentation. This is inconvenient and also give the impression that the Radix CLI is not fully supported.

**Describe the solution you'd like**
Basic documentation of the Radix CLI available in the Radix Web Console. The detailed documentation available from the CLI tool

**Comment by emirgens** [comment]
Radix ref: [321566](https://dev.azure.com/equinor/Radix/_workitems/edit/321566)

**Comment by oyron** [comment]
Issue for CLI build-in documentation: https://github.com/equinor/radix-platform/issues/923
