### ISSUE TITLE
Viewing a scheduled job in web console returns blank page

### ISSUE THREAD

**Issue by AtleH** [equinor/radix-platform#876]
**Describe the bug**
Opening a scheduled job in the web console can return a blank page. This seems to happen if there are no jobs running. The following is from the app atleh-radixjob in the playground environment. Clicking the [job link](https://console.playground.radix.equinor.com/applications/atleh-radixjob/envs/dev/jobcomponent/compute/scheduledjob/compute-20230207112818-mp6tzie6) returns a blank page in the browser.

![image](https://user-images.githubusercontent.com/551584/217233993-750c6d85-5958-4371-95f6-9b88c3b66fca.png)

The browser dev console reports an error like this:

```Javascript
react_devtools_backend.js:4012 
        
       TypeError: Cannot read properties of undefined (reading 'name')
    at w (index.tsx:189:33)
    at sa (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ac (react-dom.production.min.js:250:347)
    at Nc (react-dom.production.min.js:250:278)
    at kc (react-dom.production.min.js:250:138)
    at bc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vo (react-dom.production.min.js:122:325)
```

**To Reproduce**
1. Go to Playground -> atleh-radixjob -> dev -> compute -> scheduled jobs
2. Click on one of the jobs
3. The browser shows a blank page.

**Expected behavior**
A web page containing status information about the job, including the console output.

**Screenshots**
See above.

**Application name in Radix**
atleh-radixjob

**Application component**
compute

**Cluster**
- [ ] Production EU
- [X] Playground

**Additional context**

**Comment by emirgens** [comment]
Radix ref.: [321585](https://dev.azure.com/equinor/Radix/_workitems/edit/321585)

**Comment by emirgens** [comment]
Atle, we have done some changes to the job feature in the last sprints, this is now ready to be deployed including a fix for this issue. Closing this.

**Comment by AtleH** [comment]
2 days from reported bug to fix in production! YOU ARE THE BEST!
