### ISSUE TITLE
imageTagName as parameter radix deploy

### ISSUE THREAD

**Issue by oyron** [equinor/radix-platform#911]
This feature has been prioritized for implementation.

**Is your feature request related to a problem? Please describe.**
For deploy only scenarios it is cumbersome to update the radixconfig file when deploying new images

**Describe the solution you'd like**
The ability to pass imageTagName as parameter to radix deploy jobs from GitHub actions and Radix CLI

**Describe alternatives you've considered**
We have considered not implementing this feature, staying with the process of updating the radixconfig.yaml file

**Comment by satr** [comment]
- [ ] add an option to CLI
- [ ] add an option to radix-operator
- [ ] add an option to radix-pipeline
