### ISSUE TITLE
Show replica termination state in WebConsole

### ISSUE THREAD

**Issue by oyron** [equinor/radix-platform#915]
When a container of a replica stopped or restarted in some reason (failure, out of memory kill, etc.), pod description contains termination state of the `containerStates` with timestamps and a reason. It would be valuable to show this in addition to "Restart count" shown now.

**Comment by satr** [comment]
- [ ] Add last termination message in radix-api
- [ ] Show termination state in the web-console

**Comment by oyron** [comment]
Feature implemented and deployed
